// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_description_screen_init(void)
{
    ui_description = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_description, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_description, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_description, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_description, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_description, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_description, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DescriptionScheduleItemScreen = lv_obj_create(ui_description);
    lv_obj_set_width(ui_DescriptionScheduleItemScreen, 320);
    lv_obj_set_height(ui_DescriptionScheduleItemScreen, 240);
    lv_obj_set_align(ui_DescriptionScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DescriptionScheduleItemScreen,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_DescriptionScheduleItemScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_DescriptionScheduleItemScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DescriptionScheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DescriptionScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCloseButtonDescriptionScheduleItem = lv_obj_create(ui_DescriptionScheduleItemScreen);
    lv_obj_set_width(ui_PanelCloseButtonDescriptionScheduleItem, 30);
    lv_obj_set_height(ui_PanelCloseButtonDescriptionScheduleItem, 30);
    lv_obj_set_x(ui_PanelCloseButtonDescriptionScheduleItem, 136);
    lv_obj_set_y(ui_PanelCloseButtonDescriptionScheduleItem, -100);
    lv_obj_set_align(ui_PanelCloseButtonDescriptionScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCloseButtonDescriptionScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCloseButtonDescriptionScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCloseButtonDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCloseButtonDescriptionScheduleItem = lv_label_create(ui_PanelCloseButtonDescriptionScheduleItem);
    lv_obj_set_width(ui_LabelCloseButtonDescriptionScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCloseButtonDescriptionScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCloseButtonDescriptionScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCloseButtonDescriptionScheduleItem, "X");
    lv_obj_set_style_text_color(ui_LabelCloseButtonDescriptionScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCloseButtonDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTextAreaDescriptionScheduleItem = lv_obj_create(ui_DescriptionScheduleItemScreen);
    lv_obj_set_width(ui_PanelTextAreaDescriptionScheduleItem, 300);
    lv_obj_set_height(ui_PanelTextAreaDescriptionScheduleItem, 50);
    lv_obj_set_x(ui_PanelTextAreaDescriptionScheduleItem, 0);
    lv_obj_set_y(ui_PanelTextAreaDescriptionScheduleItem, 20);
    lv_obj_set_align(ui_PanelTextAreaDescriptionScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelTextAreaDescriptionScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTextAreaDescriptionScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTextAreaDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTextAreaDescriptionScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTextAreaDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTextAreaDescriptionScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTextAreaDescriptionScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTextAreaDescriptionScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTextAreaDescriptionScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaDescriptionsScheduleItem = lv_textarea_create(ui_PanelTextAreaDescriptionScheduleItem);
    lv_obj_set_width(ui_TextAreaDescriptionsScheduleItem, 290);
    lv_obj_set_height(ui_TextAreaDescriptionsScheduleItem, 40);
    lv_obj_set_align(ui_TextAreaDescriptionsScheduleItem, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaDescriptionsScheduleItem, " ");
    lv_textarea_set_placeholder_text(ui_TextAreaDescriptionsScheduleItem, "Enter here...");



    ui_KeyboardDescriptionsScheduleItem = lv_keyboard_create(ui_DescriptionScheduleItemScreen);
    lv_obj_set_width(ui_KeyboardDescriptionsScheduleItem, 310);
    lv_obj_set_height(ui_KeyboardDescriptionsScheduleItem, 149);
    lv_obj_set_x(ui_KeyboardDescriptionsScheduleItem, 0);
    lv_obj_set_y(ui_KeyboardDescriptionsScheduleItem, 10);
    lv_obj_set_align(ui_KeyboardDescriptionsScheduleItem, LV_ALIGN_BOTTOM_MID);

    ui_LabelTitleDescriptionScheduleItem = lv_label_create(ui_description);
    lv_obj_set_width(ui_LabelTitleDescriptionScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleDescriptionScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitleDescriptionScheduleItem, 0);
    lv_obj_set_y(ui_LabelTitleDescriptionScheduleItem, 12);
    lv_obj_set_align(ui_LabelTitleDescriptionScheduleItem, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleDescriptionScheduleItem, "Description");
    lv_obj_set_style_text_color(ui_LabelTitleDescriptionScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelCloseButtonDescriptionScheduleItem, ui_event_PanelCloseButtonDescriptionScheduleItem,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaDescriptionsScheduleItem, ui_event_TextAreaDescriptionScheduleItem, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardDescriptionsScheduleItem, ui_TextAreaDescriptionsScheduleItem);

}
