// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_DevicesAreaScreen_screen_init(void)
{
    ui_DevicesAreaScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DevicesAreaScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DevicesAreaScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DevicesAreaScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DevicesAreaScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DevicesAreaScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DevicesAreaScreen_screen = lv_obj_create(ui_DevicesAreaScreen);
    lv_obj_set_width(ui_DevicesAreaScreen_screen, 320);
    lv_obj_set_height(ui_DevicesAreaScreen_screen, 240);
    lv_obj_set_align(ui_DevicesAreaScreen_screen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DevicesAreaScreen_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DevicesAreaScreen_screen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DevicesAreaScreen_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DevicesAreaScreen_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDevicesAreaScreen_screen = lv_obj_create(ui_DevicesAreaScreen_screen);
    lv_obj_set_width(ui_PanelDevicesAreaScreen_screen, 270);
    lv_obj_set_height(ui_PanelDevicesAreaScreen_screen, 200);
    lv_obj_set_align(ui_PanelDevicesAreaScreen_screen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelDevicesAreaScreen_screen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelDevicesAreaScreen_screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelDevicesAreaScreen_screen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_PanelDevicesAreaScreen_screen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDevicesAreaScreen_screen, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDevicesAreaScreen_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDevicesAreaScreen_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDevicesAreaScreen_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea1DevicesArea = lv_obj_create(ui_PanelDevicesAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea1DevicesArea, 250);
    lv_obj_set_height(ui_PanelArea1DevicesArea, 50);
    lv_obj_set_x(ui_PanelArea1DevicesArea, 0);
    lv_obj_set_y(ui_PanelArea1DevicesArea, 2);
    lv_obj_set_align(ui_PanelArea1DevicesArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea1DevicesArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea1DevicesArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea1DevicesArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea1DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea1DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea1DevicesArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea1DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea1DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea1DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea1DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea1DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea1DevicesArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea1DevicesArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea1DevicesArea = lv_label_create(ui_PanelArea1DevicesArea);
    lv_obj_set_width(ui_LabelArea1DevicesArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea1DevicesArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea1DevicesArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea1DevicesArea, "Area 1");
    lv_obj_set_style_text_color(ui_LabelArea1DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea1DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea1DevicesArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea2DevicesArea = lv_obj_create(ui_PanelDevicesAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea2DevicesArea, 250);
    lv_obj_set_height(ui_PanelArea2DevicesArea, 50);
    lv_obj_set_x(ui_PanelArea2DevicesArea, 0);
    lv_obj_set_y(ui_PanelArea2DevicesArea, 2);
    lv_obj_set_align(ui_PanelArea2DevicesArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea2DevicesArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea2DevicesArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea2DevicesArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea2DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea2DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea2DevicesArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea2DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea2DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea2DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea2DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea2DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea2DevicesArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea2DevicesArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea2DevicesArea = lv_label_create(ui_PanelArea2DevicesArea);
    lv_obj_set_width(ui_LabelArea2DevicesArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea2DevicesArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea2DevicesArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea2DevicesArea, "Area 2");
    lv_obj_set_style_text_color(ui_LabelArea2DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea2DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea2DevicesArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea3DevicesArea = lv_obj_create(ui_PanelDevicesAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea3DevicesArea, 250);
    lv_obj_set_height(ui_PanelArea3DevicesArea, 50);
    lv_obj_set_x(ui_PanelArea3DevicesArea, 0);
    lv_obj_set_y(ui_PanelArea3DevicesArea, 2);
    lv_obj_set_align(ui_PanelArea3DevicesArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea3DevicesArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea3DevicesArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea3DevicesArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea3DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea3DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea3DevicesArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea3DevicesArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea3DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea3DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea3DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea3DevicesArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea3DevicesArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea3DevicesArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea3DevicesArea = lv_label_create(ui_PanelArea3DevicesArea);
    lv_obj_set_width(ui_LabelArea3DevicesArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea3DevicesArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea3DevicesArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea3DevicesArea, "Area 3");
    lv_obj_set_style_text_color(ui_LabelArea3DevicesArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea3DevicesArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea3DevicesArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_DevicesAreaScreen, ui_event_DevicesAreaScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea1DevicesArea, ui_event_PanelArea1DevicesArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea2DevicesArea, ui_event_PanelArea2DevicesArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea3DevicesArea, ui_event_PanelArea3DevicesArea, LV_EVENT_ALL, NULL);
    
}
