// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_Flow1_screen_init(void)
{
    ui_Flow1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Flow1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_Flow1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Flow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Flow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Flow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Flow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flow1ScheduleItemScreen = lv_obj_create(ui_Flow1);
    lv_obj_set_width(ui_Flow1ScheduleItemScreen, 320);
    lv_obj_set_height(ui_Flow1ScheduleItemScreen, 240);
    lv_obj_set_align(ui_Flow1ScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Flow1ScheduleItemScreen,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_Flow1ScheduleItemScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Flow1ScheduleItemScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Flow1ScheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Flow1ScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleFlow1ScheduleItem = lv_label_create(ui_Flow1ScheduleItemScreen);
    lv_obj_set_width(ui_LabelTitleFlow1ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleFlow1ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleFlow1ScheduleItem, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleFlow1ScheduleItem, "Flow 1");
    lv_obj_set_style_text_color(ui_LabelTitleFlow1ScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCloseButtonFlow1ScheduleItem = lv_obj_create(ui_Flow1ScheduleItemScreen);
    lv_obj_set_width(ui_PanelCloseButtonFlow1ScheduleItem, 30);
    lv_obj_set_height(ui_PanelCloseButtonFlow1ScheduleItem, 30);
    lv_obj_set_x(ui_PanelCloseButtonFlow1ScheduleItem, 136);
    lv_obj_set_y(ui_PanelCloseButtonFlow1ScheduleItem, -100);
    lv_obj_set_align(ui_PanelCloseButtonFlow1ScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCloseButtonFlow1ScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCloseButtonFlow1ScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCloseButtonFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCloseButtonFlow1ScheduleItem = lv_label_create(ui_PanelCloseButtonFlow1ScheduleItem);
    lv_obj_set_width(ui_LabelCloseButtonFlow1ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCloseButtonFlow1ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCloseButtonFlow1ScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCloseButtonFlow1ScheduleItem, "X");
    lv_obj_set_style_text_color(ui_LabelCloseButtonFlow1ScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCloseButtonFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_PanelTextAreaFlow1ScheduleItem = lv_obj_create(ui_Flow1ScheduleItemScreen);
    lv_obj_set_width(ui_PanelTextAreaFlow1ScheduleItem, 300);
    lv_obj_set_height(ui_PanelTextAreaFlow1ScheduleItem, 50);
    lv_obj_set_x(ui_PanelTextAreaFlow1ScheduleItem, 0);
    lv_obj_set_y(ui_PanelTextAreaFlow1ScheduleItem, -60);
    lv_obj_set_align(ui_PanelTextAreaFlow1ScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTextAreaFlow1ScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTextAreaFlow1ScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTextAreaFlow1ScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTextAreaFlow1ScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTextAreaFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTextAreaFlow1ScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTextAreaFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTextAreaFlow1ScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTextAreaFlow1ScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTextAreaFlow1ScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTextAreaFlow1ScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TextAreaFlow1ScheduleItem = lv_textarea_create(ui_PanelTextAreaFlow1ScheduleItem);
    lv_obj_set_width(ui_TextAreaFlow1ScheduleItem, 226);
    lv_obj_set_height(ui_TextAreaFlow1ScheduleItem, 37);
    lv_obj_set_x(ui_TextAreaFlow1ScheduleItem, 7);
    lv_obj_set_y(ui_TextAreaFlow1ScheduleItem, 26);
    lv_obj_set_align(ui_TextAreaFlow1ScheduleItem, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaFlow1ScheduleItem, "111");
    lv_textarea_set_placeholder_text(ui_TextAreaFlow1ScheduleItem, "Enter here...");

    ui_LabelUnitFlow1ScheduleItem = lv_label_create(ui_PanelTextAreaFlow1ScheduleItem);
    lv_obj_set_width(ui_LabelUnitFlow1ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnitFlow1ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnitFlow1ScheduleItem, 121);
    lv_obj_set_y(ui_LabelUnitFlow1ScheduleItem, 34);
    lv_obj_set_align(ui_LabelUnitFlow1ScheduleItem, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelUnitFlow1ScheduleItem, "(l)");
    lv_obj_set_style_text_color(ui_LabelUnitFlow1ScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnitFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitFlow1ScheduleItem, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardFlow1ScheduleItem = lv_keyboard_create(ui_Flow1ScheduleItemScreen);
    lv_keyboard_set_mode(ui_KeyboardFlow1ScheduleItem, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardFlow1ScheduleItem, 310);
    lv_obj_set_height(ui_KeyboardFlow1ScheduleItem, 149);
    lv_obj_set_x(ui_KeyboardFlow1ScheduleItem, 0);
    lv_obj_set_y(ui_KeyboardFlow1ScheduleItem, 10);
    lv_obj_set_align(ui_KeyboardFlow1ScheduleItem, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_PanelCloseButtonFlow1ScheduleItem, ui_event_PanelCloseButtonFlow1ScheduleItem,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaFlow1ScheduleItem, ui_event_TextAreaFlow1ScheduleItem, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardFlow1ScheduleItem, ui_TextAreaFlow1ScheduleItem);

}
