// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ManualScreen_screen_init(void)
{
    ui_ManualScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ManualScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ManualScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManualScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_ManualScreen);
    lv_obj_set_width(ui_Panel35, 320);
    lv_obj_set_height(ui_Panel35, 240);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel35, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel36 = lv_obj_create(ui_Panel35);
    lv_obj_set_width(ui_Panel36, 270);
    lv_obj_set_height(ui_Panel36, 200);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel36, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel36, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_Panel36, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Panel36, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel28 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel28, 260);
    lv_obj_set_height(ui_Panel28, 65);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -84);
    lv_obj_set_y(ui_Label32, -49);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Pump1");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel28);
    lv_img_set_src(ui_Image6, &ui_img_pump_icon_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Panel28);
    lv_obj_set_width(ui_Switch1, 80);
    lv_obj_set_height(ui_Switch1, 40);
    lv_obj_set_x(ui_Switch1, 31);
    lv_obj_set_y(ui_Switch1, -37);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x0EE930), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Panel27 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel27, 260);
    lv_obj_set_height(ui_Panel27, 65);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -63);
    lv_obj_set_y(ui_Label29, 35);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Pump2");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Panel27);
    lv_img_set_src(ui_Image7, &ui_img_pump_icon_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_Panel27);
    lv_obj_set_width(ui_Switch2, 80);
    lv_obj_set_height(ui_Switch2, 40);
    lv_obj_set_x(ui_Switch2, 33);
    lv_obj_set_y(ui_Switch2, 35);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x0EE930), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}
