// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_Notification_screen_init(void)
{
    ui_Notification = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Notification, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_Notification, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Notification, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Notification, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Notification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Notification, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Notification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotificationScreen = lv_obj_create(ui_Notification);
    lv_obj_set_width(ui_NotificationScreen, 320);
    lv_obj_set_height(ui_NotificationScreen, 240);
    lv_obj_set_align(ui_NotificationScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NotificationScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_NotificationScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_NotificationScreen,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_NotificationScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_NotificationScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NotificationScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotificationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NotificationScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NotificationScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NotificationScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NotificationScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleNotification = lv_label_create(ui_NotificationScreen);
    lv_obj_set_width(ui_LabelTitleNotification, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleNotification, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleNotification, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleNotification, "Notification");
    lv_obj_set_style_text_color(ui_LabelTitleNotification, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleNotification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitleNotification, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationItem1 = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_PanelNotificationItem1, 310);
    lv_obj_set_height(ui_PanelNotificationItem1, 70);
    lv_obj_set_x(ui_PanelNotificationItem1, -11);
    lv_obj_set_y(ui_PanelNotificationItem1, 101);
    lv_obj_set_align(ui_PanelNotificationItem1, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelNotificationItem1, LV_DIR_HOR);

    ui_LabelNotificationItem1 = lv_label_create(ui_PanelNotificationItem1);
    lv_obj_set_width(ui_LabelNotificationItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotificationItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotificationItem1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotificationItem1, "(2024-12-04 16:10) Schedule 1: 75%");
    lv_obj_set_style_text_font(ui_LabelNotificationItem1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationItem2 = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_PanelNotificationItem2, 310);
    lv_obj_set_height(ui_PanelNotificationItem2, 70);
    lv_obj_set_x(ui_PanelNotificationItem2, -11);
    lv_obj_set_y(ui_PanelNotificationItem2, 101);
    lv_obj_set_align(ui_PanelNotificationItem2, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelNotificationItem2, LV_DIR_HOR);

    ui_LabelNotificationItem2 = lv_label_create(ui_PanelNotificationItem2);
    lv_obj_set_width(ui_LabelNotificationItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotificationItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotificationItem2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotificationItem2, "(2024-12-04 15:30) Schedule 1: 50%");
    lv_obj_set_style_text_font(ui_LabelNotificationItem2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationItem3 = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_PanelNotificationItem3, 310);
    lv_obj_set_height(ui_PanelNotificationItem3, 70);
    lv_obj_set_x(ui_PanelNotificationItem3, -11);
    lv_obj_set_y(ui_PanelNotificationItem3, 101);
    lv_obj_set_align(ui_PanelNotificationItem3, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelNotificationItem3, LV_DIR_HOR);

    ui_LabelNotificationItem3 = lv_label_create(ui_PanelNotificationItem3);
    lv_obj_set_width(ui_LabelNotificationItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotificationItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotificationItem3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotificationItem3, "(2024-12-04 15:00) Schedule 1: 25%");
    lv_obj_set_style_text_font(ui_LabelNotificationItem3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationItem4 = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_PanelNotificationItem4, 310);
    lv_obj_set_height(ui_PanelNotificationItem4, 70);
    lv_obj_set_x(ui_PanelNotificationItem4, -11);
    lv_obj_set_y(ui_PanelNotificationItem4, 101);
    lv_obj_set_align(ui_PanelNotificationItem4, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelNotificationItem4, LV_DIR_HOR);

    ui_LabelNotificationItem4 = lv_label_create(ui_PanelNotificationItem4);
    lv_obj_set_width(ui_LabelNotificationItem4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotificationItem4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotificationItem4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotificationItem4, "(2024-12-04 15:00) Schedule 1: 25%");
    lv_obj_set_style_text_font(ui_LabelNotificationItem4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationItem5 = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_PanelNotificationItem5, 310);
    lv_obj_set_height(ui_PanelNotificationItem5, 70);
    lv_obj_set_x(ui_PanelNotificationItem5, -11);
    lv_obj_set_y(ui_PanelNotificationItem5, 101);
    lv_obj_set_align(ui_PanelNotificationItem5, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelNotificationItem5, LV_DIR_HOR);

    ui_LabelNotificationItem5 = lv_label_create(ui_PanelNotificationItem5);
    lv_obj_set_width(ui_LabelNotificationItem5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotificationItem5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNotificationItem5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotificationItem5, "(2024-12-04 15:00) Schedule 1: 25%");
    lv_obj_set_style_text_font(ui_LabelNotificationItem5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLoadingNotificationScreen = lv_obj_create(ui_Notification);
    lv_obj_set_width(ui_PanelLoadingNotificationScreen, 320);
    lv_obj_set_height(ui_PanelLoadingNotificationScreen, 240);
    lv_obj_set_align(ui_PanelLoadingNotificationScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoadingNotificationScreen, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_PanelLoadingNotificationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoadingNotificationScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoadingNotificationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoadingNotificationScreen = lv_spinner_create(ui_PanelLoadingNotificationScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoadingNotificationScreen, 80);
    lv_obj_set_height(ui_SpinnerLoadingNotificationScreen, 80);
    lv_obj_set_align(ui_SpinnerLoadingNotificationScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLoadingNotificationScreen, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LabelLoadingNotificationScreen = lv_label_create(ui_PanelLoadingNotificationScreen);
    lv_obj_set_width(ui_LabelLoadingNotificationScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoadingNotificationScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoadingNotificationScreen, 0);
    lv_obj_set_y(ui_LabelLoadingNotificationScreen, 75);
    lv_obj_set_align(ui_LabelLoadingNotificationScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoadingNotificationScreen, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoadingNotificationScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoadingNotificationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT); 

    lv_obj_add_event_cb(ui_Notification, ui_event_Notification, LV_EVENT_ALL, NULL);

}
