// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_SoidNitro_screen_init(void)
{
    ui_SoidNitro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SoidNitro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SoidNitro, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidNitro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SoidNitro, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SoidNitro, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoidNitroScreen = lv_obj_create(ui_SoidNitro);
    lv_obj_set_width(ui_SoidNitroScreen, 320);
    lv_obj_set_height(ui_SoidNitroScreen, 240);
    lv_obj_set_align(ui_SoidNitroScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoidNitroScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SoidNitroScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SoidNitroScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidNitroScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartSoidNitro = lv_chart_create(ui_SoidNitroScreen);
    lv_obj_set_width(ui_ChartSoidNitro, 249);
    lv_obj_set_height(ui_ChartSoidNitro, 155);
    lv_obj_set_x(ui_ChartSoidNitro, 0);
    lv_obj_set_y(ui_ChartSoidNitro, 20);
    lv_obj_set_align(ui_ChartSoidNitro, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartSoidNitro, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartSoidNitro, 8);
    lv_chart_set_axis_tick(ui_ChartSoidNitro, LV_CHART_AXIS_PRIMARY_X, 1, 0, 8, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidNitro, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidNitro, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    ui_ChartSoidNitro_series_1 = lv_chart_add_series(ui_ChartSoidNitro, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartSoidNitro_series_1_array[] = { 10, 20, 4, 80, 40, 70, 25, 96 };
    lv_chart_set_ext_y_array(ui_ChartSoidNitro, ui_ChartSoidNitro_series_1, ui_ChartSoidNitro_series_1_array);



    ui_labelTitleSoidNitro = lv_label_create(ui_SoidNitroScreen);
    lv_obj_set_width(ui_labelTitleSoidNitro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTitleSoidNitro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTitleSoidNitro, 0);
    lv_obj_set_y(ui_labelTitleSoidNitro, -90);
    lv_obj_set_align(ui_labelTitleSoidNitro, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTitleSoidNitro, "Nitro");
    lv_obj_set_style_text_color(ui_labelTitleSoidNitro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTitleSoidNitro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTitleSoidNitro, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SoidNitro, ui_event_SoidNitro, LV_EVENT_ALL, NULL);
}
