// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ScheduleScreen_screen_init(void)
{
    ui_ScheduleScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScheduleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainScheduleScreen = lv_obj_create(ui_ScheduleScreen);
    lv_obj_set_width(ui_MainScheduleScreen, 320);
    lv_obj_set_height(ui_MainScheduleScreen, 240);
    lv_obj_set_align(ui_MainScheduleScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainScheduleScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainScheduleScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_MainScheduleScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_MainScheduleScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainScheduleScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScheduleScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleScheduleScreen = lv_label_create(ui_MainScheduleScreen);
    lv_obj_set_width(ui_TitleScheduleScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleScheduleScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleScheduleScreen, -135);
    lv_obj_set_y(ui_TitleScheduleScreen, -104);
    lv_obj_set_align(ui_TitleScheduleScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleScheduleScreen, "SCHEDULES");
    lv_obj_set_style_text_color(ui_TitleScheduleScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleScheduleScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleScheduleScreen, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScheduleScreen, ui_event_ScheduleScreen, LV_EVENT_ALL, NULL);
    // ui_Panel2 = lv_obj_create(ui_MainScheduleScreen);
    // lv_obj_set_width(ui_Panel2, 320);
    // lv_obj_set_height(ui_Panel2, 50);
    // lv_obj_set_x(ui_Panel2, 0);
    // lv_obj_set_y(ui_Panel2, -45);
    // lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    // lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    // lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Label2 = lv_label_create(ui_Panel2);
    // lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label2, "10:10");
    // lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Panel3 = lv_obj_create(ui_Panel2);
    // lv_obj_set_width(ui_Panel3, 125);
    // lv_obj_set_height(ui_Panel3, 50);
    // lv_obj_set_x(ui_Panel3, 2);
    // lv_obj_set_y(ui_Panel3, 0);
    // lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    // lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    // lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    // lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_pad_row(ui_Panel3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_column(ui_Panel3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    // ui_Label3 = lv_label_create(ui_Panel3);
    // lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label3, "700");
    // lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0xFECACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_left(ui_Label3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_right(ui_Label3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_top(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_bottom(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Label4 = lv_label_create(ui_Panel3);
    // lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label4, "500");
    // lv_obj_set_style_bg_color(ui_Label4, lv_color_hex(0xBFDBFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_left(ui_Label4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_right(ui_Label4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_top(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_bottom(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Label5 = lv_label_create(ui_Panel3);
    // lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label5, "800");
    // lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0xFEF08A), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_left(ui_Label5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_right(ui_Label5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_top(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_pad_bottom(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Label7 = lv_label_create(ui_Panel2);
    // lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label7, "Every day");

    // ui_Switch1 = lv_switch_create(ui_Panel2);
    // lv_obj_set_width(ui_Switch1, 50);
    // lv_obj_set_height(ui_Switch1, 25);
    // lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);



}
