// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_SoidPhotpho_screen_init(void)
{
    ui_SoidPhotpho = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SoidPhotpho, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SoidPhotpho, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidPhotpho, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SoidPhotpho, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SoidPhotpho, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoidPhotphoScreen = lv_obj_create(ui_SoidPhotpho);
    lv_obj_set_width(ui_SoidPhotphoScreen, 320);
    lv_obj_set_height(ui_SoidPhotphoScreen, 240);
    lv_obj_set_align(ui_SoidPhotphoScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoidPhotphoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SoidPhotphoScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SoidPhotphoScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidPhotphoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartSoidPhotpho = lv_chart_create(ui_SoidPhotphoScreen);
    lv_obj_set_width(ui_ChartSoidPhotpho, 249);
    lv_obj_set_height(ui_ChartSoidPhotpho, 155);
    lv_obj_set_x(ui_ChartSoidPhotpho, 0);
    lv_obj_set_y(ui_ChartSoidPhotpho, 20);
    lv_obj_set_align(ui_ChartSoidPhotpho, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartSoidPhotpho, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartSoidPhotpho, 8);
    lv_chart_set_axis_tick(ui_ChartSoidPhotpho, LV_CHART_AXIS_PRIMARY_X, 1, 0, 8, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidPhotpho, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidPhotpho, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    ui_ChartSoidPhotpho_series_1 = lv_chart_add_series(ui_ChartSoidPhotpho, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartSoidPhotpho_series_1_array[] = { 10, 20, 4, 80, 40, 70, 25, 96 };
    lv_chart_set_ext_y_array(ui_ChartSoidPhotpho, ui_ChartSoidPhotpho_series_1, ui_ChartSoidPhotpho_series_1_array);



    ui_labelTitleSoidPhotpho = lv_label_create(ui_SoidPhotphoScreen);
    lv_obj_set_width(ui_labelTitleSoidPhotpho, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTitleSoidPhotpho, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTitleSoidPhotpho, 0);
    lv_obj_set_y(ui_labelTitleSoidPhotpho, -90);
    lv_obj_set_align(ui_labelTitleSoidPhotpho, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTitleSoidPhotpho, "Photpho");
    lv_obj_set_style_text_color(ui_labelTitleSoidPhotpho, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTitleSoidPhotpho, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTitleSoidPhotpho, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_SoidPhotpho, ui_event_SoidPhotpho, LV_EVENT_ALL, NULL);
}
