// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_SensorsAreaScreen_screen_init(void)
{
    ui_SensorsAreaScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorsAreaScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SensorsAreaScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorsAreaScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SensorsAreaScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SensorsAreaScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorsAreaScreen_screen = lv_obj_create(ui_SensorsAreaScreen);
    lv_obj_set_width(ui_SensorsAreaScreen_screen, 320);
    lv_obj_set_height(ui_SensorsAreaScreen_screen, 240);
    lv_obj_set_align(ui_SensorsAreaScreen_screen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SensorsAreaScreen_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SensorsAreaScreen_screen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SensorsAreaScreen_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorsAreaScreen_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensorsAreaScreen_screen = lv_obj_create(ui_SensorsAreaScreen_screen);
    lv_obj_set_width(ui_PanelSensorsAreaScreen_screen, 270);
    lv_obj_set_height(ui_PanelSensorsAreaScreen_screen, 200);
    lv_obj_set_align(ui_PanelSensorsAreaScreen_screen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSensorsAreaScreen_screen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSensorsAreaScreen_screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_PanelSensorsAreaScreen_screen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_PanelSensorsAreaScreen_screen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensorsAreaScreen_screen, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensorsAreaScreen_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSensorsAreaScreen_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSensorsAreaScreen_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea1SensorsArea = lv_obj_create(ui_PanelSensorsAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea1SensorsArea, 250);
    lv_obj_set_height(ui_PanelArea1SensorsArea, 50);
    lv_obj_set_x(ui_PanelArea1SensorsArea, 0);
    lv_obj_set_y(ui_PanelArea1SensorsArea, 2);
    lv_obj_set_align(ui_PanelArea1SensorsArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea1SensorsArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea1SensorsArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea1SensorsArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea1SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea1SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea1SensorsArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea1SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea1SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea1SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea1SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea1SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea1SensorsArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea1SensorsArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea1SensorsArea = lv_label_create(ui_PanelArea1SensorsArea);
    lv_obj_set_width(ui_LabelArea1SensorsArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea1SensorsArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea1SensorsArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea1SensorsArea, "Area 1");
    lv_obj_set_style_text_color(ui_LabelArea1SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea1SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea1SensorsArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea2SensorsArea = lv_obj_create(ui_PanelSensorsAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea2SensorsArea, 250);
    lv_obj_set_height(ui_PanelArea2SensorsArea, 50);
    lv_obj_set_x(ui_PanelArea2SensorsArea, 0);
    lv_obj_set_y(ui_PanelArea2SensorsArea, 2);
    lv_obj_set_align(ui_PanelArea2SensorsArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea2SensorsArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea2SensorsArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea2SensorsArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea2SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea2SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea2SensorsArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea2SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea2SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea2SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea2SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea2SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea2SensorsArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea2SensorsArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea2SensorsArea = lv_label_create(ui_PanelArea2SensorsArea);
    lv_obj_set_width(ui_LabelArea2SensorsArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea2SensorsArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea2SensorsArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea2SensorsArea, "Area 2");
    lv_obj_set_style_text_color(ui_LabelArea2SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea2SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea2SensorsArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArea3SensorsArea = lv_obj_create(ui_PanelSensorsAreaScreen_screen);
    lv_obj_set_width(ui_PanelArea3SensorsArea, 250);
    lv_obj_set_height(ui_PanelArea3SensorsArea, 50);
    lv_obj_set_x(ui_PanelArea3SensorsArea, 0);
    lv_obj_set_y(ui_PanelArea3SensorsArea, 2);
    lv_obj_set_align(ui_PanelArea3SensorsArea, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelArea3SensorsArea, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelArea3SensorsArea, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelArea3SensorsArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelArea3SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArea3SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArea3SensorsArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArea3SensorsArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelArea3SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelArea3SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelArea3SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelArea3SensorsArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArea3SensorsArea, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelArea3SensorsArea, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelArea3SensorsArea = lv_label_create(ui_PanelArea3SensorsArea);
    lv_obj_set_width(ui_LabelArea3SensorsArea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArea3SensorsArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArea3SensorsArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArea3SensorsArea, "Area 3");
    lv_obj_set_style_text_color(ui_LabelArea3SensorsArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelArea3SensorsArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelArea3SensorsArea, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_SensorsAreaScreen, ui_event_SensorsAreaScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea1SensorsArea, ui_event_PanelArea1SensorArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea2SensorsArea, ui_event_PanelArea2SensorArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelArea3SensorsArea, ui_event_PanelArea3SensorArea, LV_EVENT_ALL, NULL);
    
}
