// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_SoidMoistureSensor_screen_init(void)
{
    ui_SoidMoistureSensor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SoidMoistureSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SoidMoistureSensor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidMoistureSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SoidMoistureSensor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SoidMoistureSensor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoidMoistureSensorScreen = lv_obj_create(ui_SoidMoistureSensor);
    lv_obj_set_width(ui_SoidMoistureSensorScreen, 320);
    lv_obj_set_height(ui_SoidMoistureSensorScreen, 240);
    lv_obj_set_align(ui_SoidMoistureSensorScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoidMoistureSensorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SoidMoistureSensorScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SoidMoistureSensorScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidMoistureSensorScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartSoidMoistureSensor = lv_chart_create(ui_SoidMoistureSensorScreen);
    lv_obj_set_width(ui_ChartSoidMoistureSensor, 249);
    lv_obj_set_height(ui_ChartSoidMoistureSensor, 155);
    lv_obj_set_x(ui_ChartSoidMoistureSensor, 0);
    lv_obj_set_y(ui_ChartSoidMoistureSensor, 20);
    lv_obj_set_align(ui_ChartSoidMoistureSensor, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartSoidMoistureSensor, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartSoidMoistureSensor, 8);
    lv_chart_set_axis_tick(ui_ChartSoidMoistureSensor, LV_CHART_AXIS_PRIMARY_X, 1, 0, 8, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidMoistureSensor, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidMoistureSensor, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ChartSoidMoistureSensor_series_1 = lv_chart_add_series(ui_ChartSoidMoistureSensor,
                                                                                  lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartSoidMoistureSensor_series_1_array[] = { 10, 20, 4, 80, 40, 70, 25, 96 };
    lv_chart_set_ext_y_array(ui_ChartSoidMoistureSensor, ui_ChartSoidMoistureSensor_series_1,
                             ui_ChartSoidMoistureSensor_series_1_array);



    ui_LabelTitleSoidMoistureSensor = lv_label_create(ui_SoidMoistureSensorScreen);
    lv_obj_set_width(ui_LabelTitleSoidMoistureSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleSoidMoistureSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitleSoidMoistureSensor, 0);
    lv_obj_set_y(ui_LabelTitleSoidMoistureSensor, -90);
    lv_obj_set_align(ui_LabelTitleSoidMoistureSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitleSoidMoistureSensor, "Soid Moisture Sensor");
    lv_obj_set_style_text_color(ui_LabelTitleSoidMoistureSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleSoidMoistureSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitleSoidMoistureSensor, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
