// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_SoidKali_screen_init(void)
{
    ui_SoidKali = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SoidKali, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SoidKali, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidKali, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SoidKali, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SoidKali, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoidKaliScreen = lv_obj_create(ui_SoidKali);
    lv_obj_set_width(ui_SoidKaliScreen, 320);
    lv_obj_set_height(ui_SoidKaliScreen, 240);
    lv_obj_set_align(ui_SoidKaliScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SoidKaliScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SoidKaliScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SoidKaliScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SoidKaliScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartSoidKali = lv_chart_create(ui_SoidKaliScreen);
    lv_obj_set_width(ui_ChartSoidKali, 249);
    lv_obj_set_height(ui_ChartSoidKali, 155);
    lv_obj_set_x(ui_ChartSoidKali, 0);
    lv_obj_set_y(ui_ChartSoidKali, 20);
    lv_obj_set_align(ui_ChartSoidKali, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartSoidKali, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartSoidKali, 8);
    lv_chart_set_axis_tick(ui_ChartSoidKali, LV_CHART_AXIS_PRIMARY_X, 1, 0, 8, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidKali, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartSoidKali, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    ui_ChartSoidKali_series_1 = lv_chart_add_series(ui_ChartSoidKali, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartSoidKali_series_1_array[] = { 10, 20, 4, 80, 40, 70, 25, 96 };
    lv_chart_set_ext_y_array(ui_ChartSoidKali, ui_ChartSoidKali_series_1, ui_ChartSoidKali_series_1_array);



    ui_LabelSoidKali = lv_label_create(ui_SoidKaliScreen);
    lv_obj_set_width(ui_LabelSoidKali, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoidKali, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSoidKali, 0);
    lv_obj_set_y(ui_LabelSoidKali, -90);
    lv_obj_set_align(ui_LabelSoidKali, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoidKali, "Kali");
    lv_obj_set_style_text_color(ui_LabelSoidKali, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSoidKali, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSoidKali, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SoidKali, ui_event_SoidKali, LV_EVENT_ALL, NULL);

}
