// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ScheduleItemScreen_screen_init(void)
{
    ui_scheduleItemScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scheduleItemScreen, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_scheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleItemScreen = lv_obj_create(ui_scheduleItemScreen);
    lv_obj_set_width(ui_PanelScheduleItemScreen, 320);
    lv_obj_set_height(ui_PanelScheduleItemScreen, 240);
    lv_obj_set_align(ui_PanelScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleItemScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScheduleItemScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_PanelHeaderScheduleItem = lv_obj_create(ui_PanelScheduleItemScreen);
    lv_obj_set_width(ui_PanelHeaderScheduleItem, 300);
    lv_obj_set_height(ui_PanelHeaderScheduleItem, 60);
    lv_obj_set_align(ui_PanelHeaderScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelHeaderScheduleItem, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_PanelHeaderScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHeaderScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeaderScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHeaderScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeaderScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonOKHeaderScheduleItem = lv_btn_create(ui_PanelHeaderScheduleItem);
    lv_obj_set_width(ui_ButtonOKHeaderScheduleItem, 70);
    lv_obj_set_height(ui_ButtonOKHeaderScheduleItem, 50);
    lv_obj_set_align(ui_ButtonOKHeaderScheduleItem, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ButtonOKHeaderScheduleItem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOKHeaderScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonOKHeaderScheduleItem, lv_color_hex(0x4264FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonOKHeaderScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOKHeaderScheduleItem = lv_label_create(ui_ButtonOKHeaderScheduleItem);
    lv_obj_set_width(ui_LabelOKHeaderScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOKHeaderScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOKHeaderScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOKHeaderScheduleItem, "OK");
    lv_obj_set_style_text_font(ui_LabelOKHeaderScheduleItem, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCancelHeaderScheduleItem = lv_btn_create(ui_PanelHeaderScheduleItem);
    lv_obj_set_width(ui_ButtonCancelHeaderScheduleItem, 70);
    lv_obj_set_height(ui_ButtonCancelHeaderScheduleItem, 50);
    lv_obj_set_align(ui_ButtonCancelHeaderScheduleItem, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ButtonCancelHeaderScheduleItem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancelHeaderScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCancelHeaderScheduleItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCancelHeaderScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCancelHeaderScheduleItem = lv_label_create(ui_ButtonCancelHeaderScheduleItem);
    lv_obj_set_width(ui_LabelCancelHeaderScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCancelHeaderScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCancelHeaderScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCancelHeaderScheduleItem, "Cancel");
    lv_obj_set_style_text_font(ui_LabelCancelHeaderScheduleItem, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleItemContainerScreen = lv_obj_create(ui_PanelScheduleItemScreen);
    lv_obj_set_width(ui_PanelScheduleItemContainerScreen, 320);
    lv_obj_set_height(ui_PanelScheduleItemContainerScreen, 240);
    lv_obj_set_x(ui_PanelScheduleItemContainerScreen, 0);
    lv_obj_set_y(ui_PanelScheduleItemContainerScreen, 70);
    lv_obj_set_align(ui_PanelScheduleItemContainerScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleItemContainerScreen, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_PanelScheduleItemContainerScreen, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_PanelScheduleItemContainerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleItemContainerScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleItemContainerScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleItemContainerScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNameContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelNameContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelNameContainerScheduleItem, 100);
    lv_obj_set_align(ui_PanelNameContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNameContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNameContainerScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNameContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelNameContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelNameContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameTitleScheduleItem = lv_label_create(ui_PanelNameContainerScheduleItem);
    lv_obj_set_width(ui_LabelNameTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameTitleScheduleItem, "Name");
    lv_obj_set_style_text_color(ui_LabelNameTitleScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNameScheduleItem = lv_obj_create(ui_PanelNameContainerScheduleItem);
    lv_obj_set_width(ui_PanelNameScheduleItem, 280);
    lv_obj_set_height(ui_PanelNameScheduleItem, 50);
    lv_obj_set_x(ui_PanelNameScheduleItem, 0);
    lv_obj_set_y(ui_PanelNameScheduleItem, 20);
    lv_obj_set_align(ui_PanelNameScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNameScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNameScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNameScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameScheduleItem = lv_label_create(ui_PanelNameScheduleItem);
    lv_obj_set_width(ui_LabelNameScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNameScheduleItem, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNameScheduleItem, " ");
    lv_obj_set_style_text_color(ui_LabelNameScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNameScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDescriptionContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelDescriptionContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelDescriptionContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelDescriptionContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelDescriptionContainerScheduleItem, 120);
    lv_obj_set_align(ui_PanelDescriptionContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelDescriptionContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDescriptionContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDescriptionContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDescriptionContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDescriptionContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDescriptionTitleScheduleItem = lv_label_create(ui_PanelDescriptionContainerScheduleItem);
    lv_obj_set_width(ui_LabelDescriptionTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDescriptionTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelDescriptionTitleScheduleItem, "Description");
    lv_obj_set_style_text_color(ui_LabelDescriptionTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDescriptionTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDescriptionScheduleItem = lv_obj_create(ui_PanelDescriptionContainerScheduleItem);
    lv_obj_set_width(ui_PanelDescriptionScheduleItem, 280);
    lv_obj_set_height(ui_PanelDescriptionScheduleItem, 50);
    lv_obj_set_x(ui_PanelDescriptionScheduleItem, 0);
    lv_obj_set_y(ui_PanelDescriptionScheduleItem, 20);
    lv_obj_set_align(ui_PanelDescriptionScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDescriptionScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDescriptionScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDescriptionScheduleItem = lv_label_create(ui_PanelDescriptionScheduleItem);
    lv_obj_set_width(ui_LabelDescriptionScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDescriptionScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDescriptionScheduleItem, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelDescriptionScheduleItem, " ");
    lv_obj_set_style_text_color(ui_LabelDescriptionScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDescriptionScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAreaContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelAreaContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelAreaContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelAreaContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelAreaContainerScheduleItem, 240);
    lv_obj_set_align(ui_PanelAreaContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelAreaContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelAreaContainerScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAreaContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelAreaContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelAreaContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAreaTitleScheduleItem = lv_label_create(ui_PanelAreaContainerScheduleItem);
    lv_obj_set_width(ui_LabelAreaTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAreaTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelAreaTitleScheduleItem, "Area");
    lv_obj_set_style_text_color(ui_LabelAreaTitleScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAreaTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAreaScheduleItem = lv_dropdown_create(ui_PanelAreaContainerScheduleItem);
    lv_dropdown_set_options(ui_DropdownAreaScheduleItem, "Area 1\nArea 2\nArea 3");
    lv_obj_set_width(ui_DropdownAreaScheduleItem, 280);
    lv_obj_set_height(ui_DropdownAreaScheduleItem, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_DropdownAreaScheduleItem, 0);
    lv_obj_set_y(ui_DropdownAreaScheduleItem, 20);
    lv_obj_set_align(ui_DropdownAreaScheduleItem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownAreaScheduleItem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_PanelPriorityContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelPriorityContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelPriorityContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelPriorityContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelPriorityContainerScheduleItem, 360);
    lv_obj_set_align(ui_PanelPriorityContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelPriorityContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPriorityContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPriorityContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPriorityContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPriorityContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPriorityTitleScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelPriorityTitleScheduleItem, "Priority");
    lv_obj_set_style_text_color(ui_LabelPriorityTitleScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderPriorityScheduleItem = lv_slider_create(ui_PanelPriorityContainerScheduleItem);
    lv_slider_set_range(ui_SliderPriorityScheduleItem, 0, 4);
    lv_slider_set_value(ui_SliderPriorityScheduleItem, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderPriorityScheduleItem) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderPriorityScheduleItem, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderPriorityScheduleItem, 240);
    lv_obj_set_height(ui_SliderPriorityScheduleItem, 10);
    lv_obj_set_x(ui_SliderPriorityScheduleItem, 0);
    lv_obj_set_y(ui_SliderPriorityScheduleItem, 7);
    lv_obj_set_align(ui_SliderPriorityScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderPriorityScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPriorityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPriorityScheduleItem, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPriorityScheduleItem, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderPriorityScheduleItem, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPriorityScheduleItem, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelPriorityItem5ScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityItem5ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityItem5ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPriorityItem5ScheduleItem, 230);
    lv_obj_set_y(ui_LabelPriorityItem5ScheduleItem, 61);
    lv_label_set_text(ui_LabelPriorityItem5ScheduleItem, "Very High");
    lv_obj_set_style_text_color(ui_LabelPriorityItem5ScheduleItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityItem5ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPriorityItem5ScheduleItem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPriorityItem4ScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityItem4ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityItem4ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPriorityItem4ScheduleItem, 181);
    lv_obj_set_y(ui_LabelPriorityItem4ScheduleItem, 61);
    lv_label_set_text(ui_LabelPriorityItem4ScheduleItem, "High");
    lv_obj_set_style_text_color(ui_LabelPriorityItem4ScheduleItem, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityItem4ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPriorityItem4ScheduleItem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPriorityItem3ScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityItem3ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityItem3ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPriorityItem3ScheduleItem, 117);
    lv_obj_set_y(ui_LabelPriorityItem3ScheduleItem, 61);
    lv_label_set_text(ui_LabelPriorityItem3ScheduleItem, "Medium");
    lv_obj_set_style_text_color(ui_LabelPriorityItem3ScheduleItem, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityItem3ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPriorityItem3ScheduleItem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPriorityItem2ScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityItem2ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityItem2ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPriorityItem2ScheduleItem, 63);
    lv_obj_set_y(ui_LabelPriorityItem2ScheduleItem, 61);
    lv_label_set_text(ui_LabelPriorityItem2ScheduleItem, "Low");
    lv_obj_set_style_text_color(ui_LabelPriorityItem2ScheduleItem, lv_color_hex(0xFDFD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityItem2ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPriorityItem2ScheduleItem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPriorityItem1ScheduleItem = lv_label_create(ui_PanelPriorityContainerScheduleItem);
    lv_obj_set_width(ui_LabelPriorityItem1ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPriorityItem1ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPriorityItem1ScheduleItem, -12);
    lv_obj_set_y(ui_LabelPriorityItem1ScheduleItem, 61);
    lv_label_set_text(ui_LabelPriorityItem1ScheduleItem, "Very Low");
    lv_obj_set_style_text_color(ui_LabelPriorityItem1ScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPriorityItem1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPriorityItem1ScheduleItem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow1ContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelFlow1ContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelFlow1ContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelFlow1ContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow1ContainerScheduleItem, 480);
    lv_obj_set_align(ui_PanelFlow1ContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelFlow1ContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow1ContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow1ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelFlow1ContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelFlow1ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow1TitleScheduleItem = lv_label_create(ui_PanelFlow1ContainerScheduleItem);
    lv_obj_set_width(ui_LabelFlow1TitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow1TitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelFlow1TitleScheduleItem, "Flow 1 (l)");
    lv_obj_set_style_text_color(ui_LabelFlow1TitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow1TitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow1ScheduleItem = lv_obj_create(ui_PanelFlow1ContainerScheduleItem);
    lv_obj_set_width(ui_PanelFlow1ScheduleItem, 280);
    lv_obj_set_height(ui_PanelFlow1ScheduleItem, 50);
    lv_obj_set_x(ui_PanelFlow1ScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow1ScheduleItem, 20);
    lv_obj_set_align(ui_PanelFlow1ScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFlow1ScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow1ScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow1ScheduleItem = lv_label_create(ui_PanelFlow1ScheduleItem);
    lv_obj_set_width(ui_LabelFlow1ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow1ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFlow1ScheduleItem, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelFlow1ScheduleItem, "1000");
    lv_obj_set_style_text_color(ui_LabelFlow1ScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow1ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow2ContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelFlow2ContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelFlow2ContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelFlow2ContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow2ContainerScheduleItem, 600);
    lv_obj_set_align(ui_PanelFlow2ContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelFlow2ContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow2ContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow2ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelFlow2ContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelFlow2ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow2TitleScheduleItem = lv_label_create(ui_PanelFlow2ContainerScheduleItem);
    lv_obj_set_width(ui_LabelFlow2TitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow2TitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelFlow2TitleScheduleItem, "Flow 2 (l)");
    lv_obj_set_style_text_color(ui_LabelFlow2TitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow2TitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow2ScheduleItem = lv_obj_create(ui_PanelFlow2ContainerScheduleItem);
    lv_obj_set_width(ui_PanelFlow2ScheduleItem, 280);
    lv_obj_set_height(ui_PanelFlow2ScheduleItem, 50);
    lv_obj_set_x(ui_PanelFlow2ScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow2ScheduleItem, 20);
    lv_obj_set_align(ui_PanelFlow2ScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFlow2ScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow2ScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow2ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow2ScheduleItem = lv_label_create(ui_PanelFlow2ScheduleItem);
    lv_obj_set_width(ui_LabelFlow2ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow2ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFlow2ScheduleItem, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelFlow2ScheduleItem, "1000");
    lv_obj_set_style_text_color(ui_LabelFlow2ScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow2ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow3ContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelFlow3ContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelFlow3ContainerScheduleItem, 100);
    lv_obj_set_x(ui_PanelFlow3ContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow3ContainerScheduleItem, 720);
    lv_obj_set_align(ui_PanelFlow3ContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelFlow3ContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow3ContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow3ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelFlow3ContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelFlow3ContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow3TitleScheduleItem = lv_label_create(ui_PanelFlow3ContainerScheduleItem);
    lv_obj_set_width(ui_LabelFlow3TitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow3TitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelFlow3TitleScheduleItem, "Flow 3 (l)");
    lv_obj_set_style_text_color(ui_LabelFlow3TitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow3TitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFlow3ScheduleItem = lv_obj_create(ui_PanelFlow3ContainerScheduleItem);
    lv_obj_set_width(ui_PanelFlow3ScheduleItem, 280);
    lv_obj_set_height(ui_PanelFlow3ScheduleItem, 50);
    lv_obj_set_x(ui_PanelFlow3ScheduleItem, 0);
    lv_obj_set_y(ui_PanelFlow3ScheduleItem, 20);
    lv_obj_set_align(ui_PanelFlow3ScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFlow3ScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelFlow3ScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFlow3ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow3ScheduleItem = lv_label_create(ui_PanelFlow3ScheduleItem);
    lv_obj_set_width(ui_LabelFlow3ScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow3ScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFlow3ScheduleItem, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelFlow3ScheduleItem, "1000");
    lv_obj_set_style_text_color(ui_LabelFlow3ScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow3ScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleContainerScheduleItem = lv_obj_create(ui_PanelScheduleItemContainerScreen);
    lv_obj_set_width(ui_PanelScheduleContainerScheduleItem, 300);
    lv_obj_set_height(ui_PanelScheduleContainerScheduleItem, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PanelScheduleContainerScheduleItem, 0);
    lv_obj_set_y(ui_PanelScheduleContainerScheduleItem, 840);
    lv_obj_set_align(ui_PanelScheduleContainerScheduleItem, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PanelScheduleContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleTitleScheduleItem = lv_label_create(ui_PanelScheduleContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_flow(ui_LabelScheduleTitleScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelScheduleTitleScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelScheduleTitleScheduleItem, "Schedule");
    lv_obj_set_style_text_color(ui_LabelScheduleTitleScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleInforContainerScheduleItem = lv_obj_create(ui_PanelScheduleContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleInforContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleInforContainerScheduleItem, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(ui_PanelScheduleInforContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleInforContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleInforContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleInforContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleInforContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleInforContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleInforContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleInforContainerScheduleItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleInforContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleInforContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleInforContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleStartTimeContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleStartTimeContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleStartTimeContainerScheduleItem, 80);
    lv_obj_set_align(ui_PanelScheduleStartTimeContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleStartTimeContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleStartTimeContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleStartTimeContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleStartTimeContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleStartTimeContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleStartTimeContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleStartTimeContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleStartTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleStartTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleStartTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleStartTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleStartTimeTitleScheduleItem = lv_label_create(ui_PanelScheduleStartTimeContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleStartTimeTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleStartTimeTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleStartTimeTitleScheduleItem, "Start Time");
    lv_obj_set_style_text_color(ui_LabelScheduleStartTimeTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleStartTimeTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleStartTimeScheduleItem = lv_obj_create(ui_PanelScheduleStartTimeContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleStartTimeScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleStartTimeScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleStartTimeScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleStartTimeScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleStartTimeScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleStartTimeScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleStartTimeScheduleItem, lv_color_hex(0x4264FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleStartTimeScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleStartTimeScheduleItem = lv_label_create(ui_PanelScheduleStartTimeScheduleItem);
    lv_obj_set_width(ui_LabelScheduleStartTimeScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleStartTimeScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleStartTimeScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleStartTimeScheduleItem, "12:50");
    lv_obj_set_style_text_color(ui_LabelScheduleStartTimeScheduleItem, lv_color_hex(0xFAFAFA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleStartTimeScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScheduleStartTimeScheduleItem, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleStopTimeContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleStopTimeContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleStopTimeContainerScheduleItem, 80);
    lv_obj_set_align(ui_PanelScheduleStopTimeContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleStopTimeContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleStopTimeContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleStopTimeContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleStopTimeContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleStopTimeContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleStopTimeContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleStopTimeContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleStopTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleStopTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleStopTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleStopTimeContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleStopTimeTitleScheduleItem = lv_label_create(ui_PanelScheduleStopTimeContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleStopTimeTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleStopTimeTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleStopTimeTitleScheduleItem, "Stop Time");
    lv_obj_set_style_text_color(ui_LabelScheduleStopTimeTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleStopTimeTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleEndTimeScheduleItem = lv_obj_create(ui_PanelScheduleStopTimeContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleEndTimeScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleEndTimeScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleEndTimeScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleEndTimeScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleEndTimeScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleEndTimeScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleEndTimeScheduleItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleEndTimeScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleEndTimeScheduleItem = lv_label_create(ui_PanelScheduleEndTimeScheduleItem);
    lv_obj_set_width(ui_LabelScheduleEndTimeScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleEndTimeScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleEndTimeScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleEndTimeScheduleItem, "13:20");
    lv_obj_set_style_text_color(ui_LabelScheduleEndTimeScheduleItem, lv_color_hex(0xFAFAFA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleEndTimeScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScheduleEndTimeScheduleItem, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleRepeatContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleRepeatContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleRepeatContainerScheduleItem, 80);
    lv_obj_set_align(ui_PanelScheduleRepeatContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleRepeatContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleRepeatContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleRepeatContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleRepeatContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleRepeatContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleRepeatContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleRepeatContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleRepeatContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleRepeatContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleRepeatContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleRepeatContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleRepeatTitleScheduleItem = lv_label_create(ui_PanelScheduleRepeatContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleRepeatTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleRepeatTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleRepeatTitleScheduleItem, "Repeat");
    lv_obj_set_style_text_color(ui_LabelScheduleRepeatTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleRepeatTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownScheduleRepeatScheduleItem = lv_dropdown_create(ui_PanelScheduleRepeatContainerScheduleItem);
    lv_dropdown_set_options(ui_DropdownScheduleRepeatScheduleItem, "Once\nDaily\nWeekly");
    lv_obj_set_width(ui_DropdownScheduleRepeatScheduleItem, 260);
    lv_obj_set_height(ui_DropdownScheduleRepeatScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownScheduleRepeatScheduleItem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownScheduleRepeatScheduleItem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_PanelScheduleWeekContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleWeekContainerScheduleItem, 80);
    lv_obj_set_align(ui_PanelScheduleWeekContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleWeekContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleWeekContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleWeekContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleWeekContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleWeekContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleWeekContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleWeekContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleWeekContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleWeekContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleWeekContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleWeekContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleWeekTitleScheduleItem = lv_label_create(ui_PanelScheduleWeekContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleWeekTitleScheduleItem, "Week");
    lv_obj_set_style_text_color(ui_LabelScheduleWeekTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleWeekTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleWeekScheduleItem = lv_obj_create(ui_PanelScheduleWeekContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleWeekScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleWeekScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleWeekScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleWeekScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleWeekScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleWeekScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleWeekScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleWeekScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleWeekItemMondayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemMondayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemMondayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemMondayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemMondayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemMondayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemMondayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemMondayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemMondayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemMondayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemMondayScheduleItem, "2");

    ui_PanelScheduleWeekItemTuesdayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemTuesdayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemTuesdayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemTuesdayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemTuesdayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemTuesdayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemTuesdayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemTuesdayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemTuesdayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemTuesdayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemTuesdayScheduleItem, "3");

    ui_PanelScheduleWeekItemWednesdayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemWednesdayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemWednesdayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemWednesdayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemWednesdayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemWednesdayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemWednesdayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemWednesdayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemWednesdayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemWednesdayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemWednesdayScheduleItem, "4");

    ui_PanelScheduleWeekItemThursdayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemThursdayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemThursdayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemThursdayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemThursdayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemThursdayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemThursdayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemThursdayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemThursdayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemThursdayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemThursdayScheduleItem, "5");

    ui_PanelScheduleWeekItemFridayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemFridayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemFridayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemFridayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemFridayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemFridayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemFridayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemFridayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemFridayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemFridayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemFridayScheduleItem, "6");

    ui_PanelScheduleWeekItemSaturdayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemSaturdayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemSaturdayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemSaturdayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemSaturdayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemSaturdayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemSaturdayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemSaturdayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemSaturdayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemSaturdayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemSaturdayScheduleItem, "7");

    ui_PanelScheduleWeekItemSundayScheduleItem = lv_obj_create(ui_PanelScheduleWeekScheduleItem);
    lv_obj_set_width(ui_PanelScheduleWeekItemSundayScheduleItem, 29);
    lv_obj_set_height(ui_PanelScheduleWeekItemSundayScheduleItem, 29);
    lv_obj_set_align(ui_PanelScheduleWeekItemSundayScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleWeekItemSundayScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScheduleWeekItemSundayScheduleItem = lv_label_create(ui_PanelScheduleWeekItemSundayScheduleItem);
    lv_obj_set_width(ui_LabelScheduleWeekItemSundayScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleWeekItemSundayScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleWeekItemSundayScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleWeekItemSundayScheduleItem, "S");

    ui_PanelScheduleDateContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleDateContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleDateContainerScheduleItem, 120);
    lv_obj_set_align(ui_PanelScheduleDateContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleDateContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleDateContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleDateContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleDateContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleDateContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleDateTitleScheduleItem = lv_label_create(ui_PanelScheduleDateContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleDateTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleDateTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleDateTitleScheduleItem, "Date");
    lv_obj_set_style_text_color(ui_LabelScheduleDateTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleDateTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleDateScheduleItem = lv_obj_create(ui_PanelScheduleDateContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleDateScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleDateScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleDateScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleDateScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleDateScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleDateScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleDateScheduleItem, lv_color_hex(0x4264FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleDateScheduleItem = lv_label_create(ui_PanelScheduleDateScheduleItem);
    lv_obj_set_width(ui_LabelScheduleDateScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleDateScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleDateScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleDateScheduleItem, "2024-04-15");
    lv_obj_set_style_text_color(ui_LabelScheduleDateScheduleItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScheduleDateScheduleItem, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleStartDateContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleStartDateContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleStartDateContainerScheduleItem, 80);
    lv_obj_set_align(ui_PanelScheduleStartDateContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleStartDateContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleStartDateContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleStartDateContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleStartDateContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleStartDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleStartDateContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleStartDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleStartDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleStartDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleStartDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleStartDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleStartDateTitleScheduleItem = lv_label_create(ui_PanelScheduleStartDateContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleStartDateTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleStartDateTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleStartDateTitleScheduleItem, "Start Date");
    lv_obj_set_style_text_color(ui_LabelScheduleStartDateTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleStartDateTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleStartDateScheduleItem = lv_obj_create(ui_PanelScheduleStartDateContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleStartDateScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleStartDateScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleStartDateScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleStartDateScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleStartDateScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleStartDateScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleStartDateScheduleItem, lv_color_hex(0x4264FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleStartDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleStartDateScheduleItem = lv_label_create(ui_PanelScheduleStartDateScheduleItem);
    lv_obj_set_width(ui_LabelScheduleStartDateScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleStartDateScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleStartDateScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleStartDateScheduleItem, "2024-04-15");
    lv_obj_set_style_text_color(ui_LabelScheduleStartDateScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleStartDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScheduleStartDateScheduleItem, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleEndDateContainerScheduleItem = lv_obj_create(ui_PanelScheduleInforContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleEndDateContainerScheduleItem, 280);
    lv_obj_set_height(ui_PanelScheduleEndDateContainerScheduleItem, 150);
    lv_obj_set_align(ui_PanelScheduleEndDateContainerScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleEndDateContainerScheduleItem, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelScheduleEndDateContainerScheduleItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelScheduleEndDateContainerScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleEndDateContainerScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleEndDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScheduleEndDateContainerScheduleItem, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScheduleEndDateContainerScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelScheduleEndDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelScheduleEndDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelScheduleEndDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelScheduleEndDateContainerScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleEndDateTitleScheduleItem = lv_label_create(ui_PanelScheduleEndDateContainerScheduleItem);
    lv_obj_set_width(ui_LabelScheduleEndDateTitleScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleEndDateTitleScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelScheduleEndDateTitleScheduleItem, "End Date");
    lv_obj_set_style_text_color(ui_LabelScheduleEndDateTitleScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleEndDateTitleScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScheduleEndDateScheduleItem = lv_obj_create(ui_PanelScheduleEndDateContainerScheduleItem);
    lv_obj_set_width(ui_PanelScheduleEndDateScheduleItem, 260);
    lv_obj_set_height(ui_PanelScheduleEndDateScheduleItem, 50);
    lv_obj_set_align(ui_PanelScheduleEndDateScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelScheduleEndDateScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelScheduleEndDateScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScheduleEndDateScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScheduleEndDateScheduleItem, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScheduleEndDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScheduleEndDateScheduleItem = lv_label_create(ui_PanelScheduleEndDateScheduleItem);
    lv_obj_set_width(ui_LabelScheduleEndDateScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScheduleEndDateScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelScheduleEndDateScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScheduleEndDateScheduleItem, "2024-06-15");
    lv_obj_set_style_text_color(ui_LabelScheduleEndDateScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScheduleEndDateScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScheduleEndDateScheduleItem, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLoadingScheduleItemScreen = lv_obj_create(ui_PanelScheduleItemScreen);
    lv_obj_set_width(ui_PanelLoadingScheduleItemScreen, 320);
    lv_obj_set_height(ui_PanelLoadingScheduleItemScreen, 240);
    lv_obj_set_align(ui_PanelLoadingScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoadingScheduleItemScreen, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_PanelLoadingScheduleItemScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoadingScheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoadingScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoadingScheduleItemScreen = lv_spinner_create(ui_PanelLoadingScheduleItemScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoadingScheduleItemScreen, 80);
    lv_obj_set_height(ui_SpinnerLoadingScheduleItemScreen, 80);
    lv_obj_set_align(ui_SpinnerLoadingScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLoadingScheduleItemScreen, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LabelLoadingScheduleItemScreen = lv_label_create(ui_PanelLoadingScheduleItemScreen);
    lv_obj_set_width(ui_LabelLoadingScheduleItemScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoadingScheduleItemScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoadingScheduleItemScreen, 0);
    lv_obj_set_y(ui_LabelLoadingScheduleItemScreen, 75);
    lv_obj_set_align(ui_LabelLoadingScheduleItemScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoadingScheduleItemScreen, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoadingScheduleItemScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoadingScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);    

    lv_obj_add_event_cb(ui_DropdownScheduleRepeatScheduleItem, ui_event_DropdownClickedScheduleRepeatScheduleItem, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemMondayScheduleItem, ui_event_PanelScheduleWeekItemMondayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemTuesdayScheduleItem, ui_event_PanelScheduleWeekItemTuesdayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemWednesdayScheduleItem, ui_event_PanelScheduleWeekItemWednesdayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemThursdayScheduleItem, ui_event_PanelScheduleWeekItemThursdayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemFridayScheduleItem, ui_event_PanelScheduleWeekItemFridayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemSaturdayScheduleItem, ui_event_PanelScheduleWeekItemSaturdayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleWeekItemSundayScheduleItem, ui_event_PanelScheduleWeekItemSundayScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonOKHeaderScheduleItem, ui_event_ButtonOKHeaderScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonCancelHeaderScheduleItem, ui_event_ButtonCancelHeaderScheduleItem, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_PanelNameScheduleItem, ui_event_PanelNameScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelDescriptionScheduleItem, ui_event_PanelDescriptionScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelFlow1ScheduleItem, ui_event_PanelFlow1ScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelFlow2ScheduleItem, ui_event_PanelFlow2ScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelFlow3ScheduleItem, ui_event_PanelFlow3ScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleStartTimeScheduleItem, ui_event_PanelScheduleStartTimeScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleEndTimeScheduleItem, ui_event_PanelScheduleEndTimeScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleDateScheduleItem, ui_event_PanelScheduleDateScheduleItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelScheduleStartDateScheduleItem, ui_event_PanelScheduleStartDateScheduleItem, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_PanelScheduleEndDateScheduleItem, ui_event_PanelScheduleEndDateScheduleItem, LV_EVENT_ALL, NULL);
}