// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ThresHoldItemScreen3_screen_init(void)
{
    ui_ThresHoldItemScreen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ThresHoldItemScreen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThresHoldItemContainer3 = lv_obj_create(ui_ThresHoldItemScreen3);
    lv_obj_set_width(ui_ThresHoldItemContainer3, 320);
    lv_obj_set_height(ui_ThresHoldItemContainer3, 240);
    lv_obj_set_align(ui_ThresHoldItemContainer3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThresHoldItemContainer3,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_ThresHoldItemContainer3, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ThresHoldItemContainer3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThresHoldItemContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThresHoldItemContainer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleThresHoldItem3 = lv_label_create(ui_ThresHoldItemContainer3);
    lv_obj_set_width(ui_LabelTitleThresHoldItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleThresHoldItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleThresHoldItem3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleThresHoldItem3, "Kali Min");
    lv_obj_set_style_text_color(ui_LabelTitleThresHoldItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleThresHoldItem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButtonXThresHoldItem3 = lv_obj_create(ui_ThresHoldItemContainer3);
    lv_obj_set_width(ui_PanelButtonXThresHoldItem3, 30);
    lv_obj_set_height(ui_PanelButtonXThresHoldItem3, 30);
    lv_obj_set_x(ui_PanelButtonXThresHoldItem3, 136);
    lv_obj_set_y(ui_PanelButtonXThresHoldItem3, -100);
    lv_obj_set_align(ui_PanelButtonXThresHoldItem3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButtonXThresHoldItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelButtonXThresHoldItem3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonXThresHoldItem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonXThresHoldItem3 = lv_label_create(ui_PanelButtonXThresHoldItem3);
    lv_obj_set_width(ui_LabelButtonXThresHoldItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonXThresHoldItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonXThresHoldItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonXThresHoldItem3, "X");
    lv_obj_set_style_text_color(ui_LabelButtonXThresHoldItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonXThresHoldItem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardThresHoldItem3 = lv_keyboard_create(ui_ThresHoldItemContainer3);
    lv_keyboard_set_mode(ui_KeyboardThresHoldItem3, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardThresHoldItem3, 310);
    lv_obj_set_height(ui_KeyboardThresHoldItem3, 149);
    lv_obj_set_x(ui_KeyboardThresHoldItem3, 0);
    lv_obj_set_y(ui_KeyboardThresHoldItem3, 10);
    lv_obj_set_align(ui_KeyboardThresHoldItem3, LV_ALIGN_BOTTOM_MID);

    ui_PanelThresHoldItemContainer3 = lv_obj_create(ui_ThresHoldItemContainer3);
    lv_obj_set_width(ui_PanelThresHoldItemContainer3, 300);
    lv_obj_set_height(ui_PanelThresHoldItemContainer3, 50);
    lv_obj_set_x(ui_PanelThresHoldItemContainer3, 0);
    lv_obj_set_y(ui_PanelThresHoldItemContainer3, -60);
    lv_obj_set_align(ui_PanelThresHoldItemContainer3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelThresHoldItemContainer3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelThresHoldItemContainer3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelThresHoldItemContainer3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelThresHoldItemContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThresHoldItemContainer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelThresHoldItemContainer3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelThresHoldItemContainer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelThresHoldItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelThresHoldItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelThresHoldItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelThresHoldItemContainer3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaThresHoldItem3 = lv_textarea_create(ui_PanelThresHoldItemContainer3);
    lv_obj_set_width(ui_TextAreaThresHoldItem3, 226);
    lv_obj_set_height(ui_TextAreaThresHoldItem3, 37);
    lv_obj_set_x(ui_TextAreaThresHoldItem3, 7);
    lv_obj_set_y(ui_TextAreaThresHoldItem3, 26);
    lv_obj_set_align(ui_TextAreaThresHoldItem3, LV_ALIGN_CENTER);



    lv_obj_add_event_cb(ui_PanelButtonXThresHoldItem3, ui_event_PanelButtonXThresHoldItem3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaThresHoldItem3, ui_event_TextAreaThresHoldItem3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardThresHoldItem3, ui_TextAreaThresHoldItem3);

}
