// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ThresHoldItemScreen6_screen_init(void)
{
    ui_ThresHoldItemScreen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ThresHoldItemScreen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThresHoldItemContainer6 = lv_obj_create(ui_ThresHoldItemScreen6);
    lv_obj_set_width(ui_ThresHoldItemContainer6, 320);
    lv_obj_set_height(ui_ThresHoldItemContainer6, 240);
    lv_obj_set_align(ui_ThresHoldItemContainer6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThresHoldItemContainer6,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_ThresHoldItemContainer6, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ThresHoldItemContainer6, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThresHoldItemContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThresHoldItemContainer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleThresHoldItem6 = lv_label_create(ui_ThresHoldItemContainer6);
    lv_obj_set_width(ui_LabelTitleThresHoldItem6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleThresHoldItem6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleThresHoldItem6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleThresHoldItem6, "Nito Max");
    lv_obj_set_style_text_color(ui_LabelTitleThresHoldItem6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleThresHoldItem6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButtonXThresHoldItem6 = lv_obj_create(ui_ThresHoldItemContainer6);
    lv_obj_set_width(ui_PanelButtonXThresHoldItem6, 30);
    lv_obj_set_height(ui_PanelButtonXThresHoldItem6, 30);
    lv_obj_set_x(ui_PanelButtonXThresHoldItem6, 136);
    lv_obj_set_y(ui_PanelButtonXThresHoldItem6, -100);
    lv_obj_set_align(ui_PanelButtonXThresHoldItem6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButtonXThresHoldItem6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelButtonXThresHoldItem6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonXThresHoldItem6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonXThresHoldItem6 = lv_label_create(ui_PanelButtonXThresHoldItem6);
    lv_obj_set_width(ui_LabelButtonXThresHoldItem6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonXThresHoldItem6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonXThresHoldItem6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonXThresHoldItem6, "X");
    lv_obj_set_style_text_color(ui_LabelButtonXThresHoldItem6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonXThresHoldItem6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardThresHoldItem6 = lv_keyboard_create(ui_ThresHoldItemContainer6);
    lv_keyboard_set_mode(ui_KeyboardThresHoldItem6, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardThresHoldItem6, 310);
    lv_obj_set_height(ui_KeyboardThresHoldItem6, 149);
    lv_obj_set_x(ui_KeyboardThresHoldItem6, 0);
    lv_obj_set_y(ui_KeyboardThresHoldItem6, 10);
    lv_obj_set_align(ui_KeyboardThresHoldItem6, LV_ALIGN_BOTTOM_MID);

    ui_PanelThresHoldItemContainer6 = lv_obj_create(ui_ThresHoldItemContainer6);
    lv_obj_set_width(ui_PanelThresHoldItemContainer6, 300);
    lv_obj_set_height(ui_PanelThresHoldItemContainer6, 50);
    lv_obj_set_x(ui_PanelThresHoldItemContainer6, 0);
    lv_obj_set_y(ui_PanelThresHoldItemContainer6, -60);
    lv_obj_set_align(ui_PanelThresHoldItemContainer6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelThresHoldItemContainer6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelThresHoldItemContainer6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelThresHoldItemContainer6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelThresHoldItemContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThresHoldItemContainer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelThresHoldItemContainer6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelThresHoldItemContainer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelThresHoldItemContainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelThresHoldItemContainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelThresHoldItemContainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelThresHoldItemContainer6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaThresHoldItem6 = lv_textarea_create(ui_PanelThresHoldItemContainer6);
    lv_obj_set_width(ui_TextAreaThresHoldItem6, 226);
    lv_obj_set_height(ui_TextAreaThresHoldItem6, 37);
    lv_obj_set_x(ui_TextAreaThresHoldItem6, 7);
    lv_obj_set_y(ui_TextAreaThresHoldItem6, 26);
    lv_obj_set_align(ui_TextAreaThresHoldItem6, LV_ALIGN_CENTER);



    lv_obj_add_event_cb(ui_PanelButtonXThresHoldItem6, ui_event_PanelButtonXThresHoldItem6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaThresHoldItem6, ui_event_TextAreaThresHoldItem6, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardThresHoldItem6, ui_TextAreaThresHoldItem6);

}
