// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ThresHoldItemScreen8_screen_init(void)
{
    ui_ThresHoldItemScreen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ThresHoldItemScreen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThresHoldItemContainer8 = lv_obj_create(ui_ThresHoldItemScreen8);
    lv_obj_set_width(ui_ThresHoldItemContainer8, 320);
    lv_obj_set_height(ui_ThresHoldItemContainer8, 240);
    lv_obj_set_align(ui_ThresHoldItemContainer8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThresHoldItemContainer8,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_ThresHoldItemContainer8, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ThresHoldItemContainer8, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThresHoldItemContainer8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThresHoldItemContainer8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleThresHoldItem8 = lv_label_create(ui_ThresHoldItemContainer8);
    lv_obj_set_width(ui_LabelTitleThresHoldItem8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleThresHoldItem8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleThresHoldItem8, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleThresHoldItem8, "Photpho Max");
    lv_obj_set_style_text_color(ui_LabelTitleThresHoldItem8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleThresHoldItem8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButtonXThresHoldItem8 = lv_obj_create(ui_ThresHoldItemContainer8);
    lv_obj_set_width(ui_PanelButtonXThresHoldItem8, 30);
    lv_obj_set_height(ui_PanelButtonXThresHoldItem8, 30);
    lv_obj_set_x(ui_PanelButtonXThresHoldItem8, 136);
    lv_obj_set_y(ui_PanelButtonXThresHoldItem8, -100);
    lv_obj_set_align(ui_PanelButtonXThresHoldItem8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButtonXThresHoldItem8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelButtonXThresHoldItem8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonXThresHoldItem8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonXThresHoldItem8 = lv_label_create(ui_PanelButtonXThresHoldItem8);
    lv_obj_set_width(ui_LabelButtonXThresHoldItem8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonXThresHoldItem8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonXThresHoldItem8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonXThresHoldItem8, "X");
    lv_obj_set_style_text_color(ui_LabelButtonXThresHoldItem8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonXThresHoldItem8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardThresHoldItem8 = lv_keyboard_create(ui_ThresHoldItemContainer8);
    lv_keyboard_set_mode(ui_KeyboardThresHoldItem8, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardThresHoldItem8, 310);
    lv_obj_set_height(ui_KeyboardThresHoldItem8, 149);
    lv_obj_set_x(ui_KeyboardThresHoldItem8, 0);
    lv_obj_set_y(ui_KeyboardThresHoldItem8, 10);
    lv_obj_set_align(ui_KeyboardThresHoldItem8, LV_ALIGN_BOTTOM_MID);

    ui_PanelThresHoldItemContainer8 = lv_obj_create(ui_ThresHoldItemContainer8);
    lv_obj_set_width(ui_PanelThresHoldItemContainer8, 300);
    lv_obj_set_height(ui_PanelThresHoldItemContainer8, 50);
    lv_obj_set_x(ui_PanelThresHoldItemContainer8, 0);
    lv_obj_set_y(ui_PanelThresHoldItemContainer8, -60);
    lv_obj_set_align(ui_PanelThresHoldItemContainer8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelThresHoldItemContainer8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelThresHoldItemContainer8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelThresHoldItemContainer8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelThresHoldItemContainer8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThresHoldItemContainer8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelThresHoldItemContainer8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelThresHoldItemContainer8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelThresHoldItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelThresHoldItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelThresHoldItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelThresHoldItemContainer8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaThresHoldItem8 = lv_textarea_create(ui_PanelThresHoldItemContainer8);
    lv_obj_set_width(ui_TextAreaThresHoldItem8, 226);
    lv_obj_set_height(ui_TextAreaThresHoldItem8, 37);
    lv_obj_set_x(ui_TextAreaThresHoldItem8, 7);
    lv_obj_set_y(ui_TextAreaThresHoldItem8, 26);
    lv_obj_set_align(ui_TextAreaThresHoldItem8, LV_ALIGN_CENTER);



    lv_obj_add_event_cb(ui_PanelButtonXThresHoldItem8, ui_event_PanelButtonXThresHoldItem8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaThresHoldItem8, ui_event_TextAreaThresHoldItem8, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardThresHoldItem8, ui_TextAreaThresHoldItem8);

}
