// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_ThresHoldItemScreen2_screen_init(void)
{
    ui_ThresHoldItemScreen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ThresHoldItemScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThresHoldItemContainer2 = lv_obj_create(ui_ThresHoldItemScreen2);
    lv_obj_set_width(ui_ThresHoldItemContainer2, 320);
    lv_obj_set_height(ui_ThresHoldItemContainer2, 240);
    lv_obj_set_align(ui_ThresHoldItemContainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThresHoldItemContainer2,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_ThresHoldItemContainer2, LV_DIR_VER);
    lv_obj_set_style_radius(ui_ThresHoldItemContainer2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThresHoldItemContainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThresHoldItemContainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleThresHoldItem2 = lv_label_create(ui_ThresHoldItemContainer2);
    lv_obj_set_width(ui_LabelTitleThresHoldItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleThresHoldItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleThresHoldItem2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleThresHoldItem2, "Temperature Max");
    lv_obj_set_style_text_color(ui_LabelTitleThresHoldItem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleThresHoldItem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelButtonXThresHoldItem2 = lv_obj_create(ui_ThresHoldItemContainer2);
    lv_obj_set_width(ui_PanelButtonXThresHoldItem2, 30);
    lv_obj_set_height(ui_PanelButtonXThresHoldItem2, 30);
    lv_obj_set_x(ui_PanelButtonXThresHoldItem2, 136);
    lv_obj_set_y(ui_PanelButtonXThresHoldItem2, -100);
    lv_obj_set_align(ui_PanelButtonXThresHoldItem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelButtonXThresHoldItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelButtonXThresHoldItem2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelButtonXThresHoldItem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonXThresHoldItem2 = lv_label_create(ui_PanelButtonXThresHoldItem2);
    lv_obj_set_width(ui_LabelButtonXThresHoldItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonXThresHoldItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonXThresHoldItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonXThresHoldItem2, "X");
    lv_obj_set_style_text_color(ui_LabelButtonXThresHoldItem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonXThresHoldItem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardThresHoldItem2 = lv_keyboard_create(ui_ThresHoldItemContainer2);
    lv_keyboard_set_mode(ui_KeyboardThresHoldItem2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardThresHoldItem2, 310);
    lv_obj_set_height(ui_KeyboardThresHoldItem2, 149);
    lv_obj_set_x(ui_KeyboardThresHoldItem2, 0);
    lv_obj_set_y(ui_KeyboardThresHoldItem2, 10);
    lv_obj_set_align(ui_KeyboardThresHoldItem2, LV_ALIGN_BOTTOM_MID);

    ui_PanelThresHoldItemContainer2 = lv_obj_create(ui_ThresHoldItemContainer2);
    lv_obj_set_width(ui_PanelThresHoldItemContainer2, 300);
    lv_obj_set_height(ui_PanelThresHoldItemContainer2, 50);
    lv_obj_set_x(ui_PanelThresHoldItemContainer2, 0);
    lv_obj_set_y(ui_PanelThresHoldItemContainer2, -60);
    lv_obj_set_align(ui_PanelThresHoldItemContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelThresHoldItemContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelThresHoldItemContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelThresHoldItemContainer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelThresHoldItemContainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelThresHoldItemContainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelThresHoldItemContainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelThresHoldItemContainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelThresHoldItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelThresHoldItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelThresHoldItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelThresHoldItemContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaThresHoldItem2 = lv_textarea_create(ui_PanelThresHoldItemContainer2);
    lv_obj_set_width(ui_TextAreaThresHoldItem2, 226);
    lv_obj_set_height(ui_TextAreaThresHoldItem2, 37);
    lv_obj_set_x(ui_TextAreaThresHoldItem2, 7);
    lv_obj_set_y(ui_TextAreaThresHoldItem2, 26);
    lv_obj_set_align(ui_TextAreaThresHoldItem2, LV_ALIGN_CENTER);



    lv_obj_add_event_cb(ui_PanelButtonXThresHoldItem2, ui_event_PanelButtonXThresHoldItem2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaThresHoldItem2, ui_event_TextAreaThresHoldItem2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardThresHoldItem2, ui_TextAreaThresHoldItem2);

}
