// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_waterProcess_screen_init(void)
{
    ui_waterProcess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_waterProcess, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_waterProcess, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_waterProcess, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_waterProcess, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterProcess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_waterProcess, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_waterProcess, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_waterProcessScreen = lv_obj_create(ui_waterProcess);
    lv_obj_set_width(ui_waterProcessScreen, 320);
    lv_obj_set_height(ui_waterProcessScreen, 240);
    lv_obj_set_align(ui_waterProcessScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_waterProcessScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_waterProcessScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_waterProcessScreen,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_waterProcessScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_waterProcessScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_waterProcessScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterProcessScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleWaterProcess = lv_label_create(ui_waterProcessScreen);
    lv_obj_set_width(ui_LabelTitleWaterProcess, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleWaterProcess, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleWaterProcess, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleWaterProcess, "Water Process");
    lv_obj_set_style_text_color(ui_LabelTitleWaterProcess, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleWaterProcess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWaterProcessItem1 = lv_obj_create(ui_waterProcessScreen);
    lv_obj_set_width(ui_PanelWaterProcessItem1, 290);
    lv_obj_set_height(ui_PanelWaterProcessItem1, 70);
    lv_obj_set_x(ui_PanelWaterProcessItem1, -11);
    lv_obj_set_y(ui_PanelWaterProcessItem1, 101);
    lv_obj_set_align(ui_PanelWaterProcessItem1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWaterProcessItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderWaterProcessItem1 = lv_slider_create(ui_PanelWaterProcessItem1);
    lv_slider_set_value(ui_SliderWaterProcessItem1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWaterProcessItem1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderWaterProcessItem1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWaterProcessItem1, 150);
    lv_obj_set_height(ui_SliderWaterProcessItem1, 10);
    lv_obj_set_x(ui_SliderWaterProcessItem1, 60);
    lv_obj_set_y(ui_SliderWaterProcessItem1, 0);
    lv_obj_set_align(ui_SliderWaterProcessItem1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SliderWaterProcessItem1, LV_STATE_DISABLED);       /// States


    ui_LabelNameWaterProcessItem1 = lv_label_create(ui_PanelWaterProcessItem1);
    lv_obj_set_width(ui_LabelNameWaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWaterProcessItem1, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimeWaterProcessItem1 = lv_obj_create(ui_PanelWaterProcessItem1);
    lv_obj_set_width(ui_PanelTimeWaterProcessItem1, 100);
    lv_obj_set_height(ui_PanelTimeWaterProcessItem1, 20);
    lv_obj_set_align(ui_PanelTimeWaterProcessItem1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelTimeWaterProcessItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelTimeWaterProcessItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimeWaterProcessItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimeWaterProcessItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimeWaterProcessItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWaterProcessItem1 = lv_label_create(ui_PanelTimeWaterProcessItem1);
    lv_obj_set_width(ui_LabelStartTimeWaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartTimeWaterProcessItem1, -20);
    lv_obj_set_y(ui_LabelStartTimeWaterProcessItem1, 0);
    lv_obj_set_align(ui_LabelStartTimeWaterProcessItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWaterProcessItem1, "08:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBetweenWaterProcessItem1 = lv_label_create(ui_PanelTimeWaterProcessItem1);
    lv_obj_set_width(ui_LabelBetweenWaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBetweenWaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBetweenWaterProcessItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBetweenWaterProcessItem1, "-");
    lv_obj_set_style_text_font(ui_LabelBetweenWaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWaterProcessItem1 = lv_label_create(ui_PanelTimeWaterProcessItem1);
    lv_obj_set_width(ui_LabelEndTimeWaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEndTimeWaterProcessItem1, 20);
    lv_obj_set_y(ui_LabelEndTimeWaterProcessItem1, 0);
    lv_obj_set_align(ui_LabelEndTimeWaterProcessItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWaterProcessItem1, "09:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue0WaterProcessItem1 = lv_label_create(ui_PanelWaterProcessItem1);
    lv_obj_set_width(ui_LabelValue0WaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue0WaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue0WaterProcessItem1, -15);
    lv_obj_set_y(ui_LabelValue0WaterProcessItem1, 20);
    lv_obj_set_align(ui_LabelValue0WaterProcessItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue0WaterProcessItem1, "0");
    lv_obj_set_style_text_font(ui_LabelValue0WaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue100WaterProcessItem1 = lv_label_create(ui_PanelWaterProcessItem1);
    lv_obj_set_width(ui_LabelValue100WaterProcessItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue100WaterProcessItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue100WaterProcessItem1, 130);
    lv_obj_set_y(ui_LabelValue100WaterProcessItem1, 20);
    lv_obj_set_align(ui_LabelValue100WaterProcessItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue100WaterProcessItem1, "100");
    lv_obj_set_style_text_font(ui_LabelValue100WaterProcessItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWaterProcessItem2 = lv_obj_create(ui_waterProcessScreen);
    lv_obj_set_width(ui_PanelWaterProcessItem2, 290);
    lv_obj_set_height(ui_PanelWaterProcessItem2, 70);
    lv_obj_set_x(ui_PanelWaterProcessItem2, -11);
    lv_obj_set_y(ui_PanelWaterProcessItem2, 101);
    lv_obj_set_align(ui_PanelWaterProcessItem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWaterProcessItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderWaterProcessItem2 = lv_slider_create(ui_PanelWaterProcessItem2);
    lv_slider_set_value(ui_SliderWaterProcessItem2, 45, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWaterProcessItem2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderWaterProcessItem2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWaterProcessItem2, 150);
    lv_obj_set_height(ui_SliderWaterProcessItem2, 10);
    lv_obj_set_x(ui_SliderWaterProcessItem2, 60);
    lv_obj_set_y(ui_SliderWaterProcessItem2, 0);
    lv_obj_set_align(ui_SliderWaterProcessItem2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SliderWaterProcessItem2, LV_STATE_DISABLED);       /// States


    ui_LabelNameWaterProcessItem2 = lv_label_create(ui_PanelWaterProcessItem2);
    lv_obj_set_width(ui_LabelNameWaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWaterProcessItem2, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimeWaterProcessItem2 = lv_obj_create(ui_PanelWaterProcessItem2);
    lv_obj_set_width(ui_PanelTimeWaterProcessItem2, 100);
    lv_obj_set_height(ui_PanelTimeWaterProcessItem2, 20);
    lv_obj_set_align(ui_PanelTimeWaterProcessItem2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelTimeWaterProcessItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelTimeWaterProcessItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimeWaterProcessItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimeWaterProcessItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimeWaterProcessItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWaterProcessItem2 = lv_label_create(ui_PanelTimeWaterProcessItem2);
    lv_obj_set_width(ui_LabelStartTimeWaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartTimeWaterProcessItem2, -20);
    lv_obj_set_y(ui_LabelStartTimeWaterProcessItem2, 0);
    lv_obj_set_align(ui_LabelStartTimeWaterProcessItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWaterProcessItem2, "08:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBetweenWaterProcessItem2 = lv_label_create(ui_PanelTimeWaterProcessItem2);
    lv_obj_set_width(ui_LabelBetweenWaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBetweenWaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBetweenWaterProcessItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBetweenWaterProcessItem2, "-");
    lv_obj_set_style_text_font(ui_LabelBetweenWaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWaterProcessItem2 = lv_label_create(ui_PanelTimeWaterProcessItem2);
    lv_obj_set_width(ui_LabelEndTimeWaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEndTimeWaterProcessItem2, 20);
    lv_obj_set_y(ui_LabelEndTimeWaterProcessItem2, 0);
    lv_obj_set_align(ui_LabelEndTimeWaterProcessItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWaterProcessItem2, "09:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue0WaterProcessItem2 = lv_label_create(ui_PanelWaterProcessItem2);
    lv_obj_set_width(ui_LabelValue0WaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue0WaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue0WaterProcessItem2, -15);
    lv_obj_set_y(ui_LabelValue0WaterProcessItem2, 20);
    lv_obj_set_align(ui_LabelValue0WaterProcessItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue0WaterProcessItem2, "0");
    lv_obj_set_style_text_font(ui_LabelValue0WaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue100WaterProcessItem2 = lv_label_create(ui_PanelWaterProcessItem2);
    lv_obj_set_width(ui_LabelValue100WaterProcessItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue100WaterProcessItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue100WaterProcessItem2, 130);
    lv_obj_set_y(ui_LabelValue100WaterProcessItem2, 20);
    lv_obj_set_align(ui_LabelValue100WaterProcessItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue100WaterProcessItem2, "100");
    lv_obj_set_style_text_font(ui_LabelValue100WaterProcessItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWaterProcessItem3 = lv_obj_create(ui_waterProcessScreen);
    lv_obj_set_width(ui_PanelWaterProcessItem3, 290);
    lv_obj_set_height(ui_PanelWaterProcessItem3, 70);
    lv_obj_set_x(ui_PanelWaterProcessItem3, -11);
    lv_obj_set_y(ui_PanelWaterProcessItem3, 101);
    lv_obj_set_align(ui_PanelWaterProcessItem3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWaterProcessItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderWaterProcessItem3 = lv_slider_create(ui_PanelWaterProcessItem3);
    lv_slider_set_value(ui_SliderWaterProcessItem3, 78, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWaterProcessItem3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderWaterProcessItem3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWaterProcessItem3, 150);
    lv_obj_set_height(ui_SliderWaterProcessItem3, 10);
    lv_obj_set_x(ui_SliderWaterProcessItem3, 60);
    lv_obj_set_y(ui_SliderWaterProcessItem3, 0);
    lv_obj_set_align(ui_SliderWaterProcessItem3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SliderWaterProcessItem3, LV_STATE_DISABLED);       /// States


    ui_LabelNameWaterProcessItem3 = lv_label_create(ui_PanelWaterProcessItem3);
    lv_obj_set_width(ui_LabelNameWaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWaterProcessItem3, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimeWaterProcessItem3 = lv_obj_create(ui_PanelWaterProcessItem3);
    lv_obj_set_width(ui_PanelTimeWaterProcessItem3, 100);
    lv_obj_set_height(ui_PanelTimeWaterProcessItem3, 20);
    lv_obj_set_align(ui_PanelTimeWaterProcessItem3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelTimeWaterProcessItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelTimeWaterProcessItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimeWaterProcessItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimeWaterProcessItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimeWaterProcessItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWaterProcessItem3 = lv_label_create(ui_PanelTimeWaterProcessItem3);
    lv_obj_set_width(ui_LabelStartTimeWaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartTimeWaterProcessItem3, -20);
    lv_obj_set_y(ui_LabelStartTimeWaterProcessItem3, 0);
    lv_obj_set_align(ui_LabelStartTimeWaterProcessItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWaterProcessItem3, "08:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBetweenWaterProcessItem3 = lv_label_create(ui_PanelTimeWaterProcessItem3);
    lv_obj_set_width(ui_LabelBetweenWaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBetweenWaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBetweenWaterProcessItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBetweenWaterProcessItem3, "-");
    lv_obj_set_style_text_font(ui_LabelBetweenWaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWaterProcessItem3 = lv_label_create(ui_PanelTimeWaterProcessItem3);
    lv_obj_set_width(ui_LabelEndTimeWaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEndTimeWaterProcessItem3, 20);
    lv_obj_set_y(ui_LabelEndTimeWaterProcessItem3, 0);
    lv_obj_set_align(ui_LabelEndTimeWaterProcessItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWaterProcessItem3, "09:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue0WaterProcessItem3 = lv_label_create(ui_PanelWaterProcessItem3);
    lv_obj_set_width(ui_LabelValue0WaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue0WaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue0WaterProcessItem3, -15);
    lv_obj_set_y(ui_LabelValue0WaterProcessItem3, 20);
    lv_obj_set_align(ui_LabelValue0WaterProcessItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue0WaterProcessItem3, "0");
    lv_obj_set_style_text_font(ui_LabelValue0WaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValue100WaterProcessItem3 = lv_label_create(ui_PanelWaterProcessItem3);
    lv_obj_set_width(ui_LabelValue100WaterProcessItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValue100WaterProcessItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValue100WaterProcessItem3, 130);
    lv_obj_set_y(ui_LabelValue100WaterProcessItem3, 20);
    lv_obj_set_align(ui_LabelValue100WaterProcessItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValue100WaterProcessItem3, "100");
    lv_obj_set_style_text_font(ui_LabelValue100WaterProcessItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
     lv_obj_add_event_cb(ui_waterProcess, ui_event_waterProcess, LV_EVENT_ALL, NULL);
}
