// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_wateringHistory_screen_init(void)
{
    ui_wateringHistory = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wateringHistory,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_wateringHistory, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_wateringHistory, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_wateringHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wateringHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wateringHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wateringHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wateringHistoryScreen = lv_obj_create(ui_wateringHistory);
    lv_obj_set_width(ui_wateringHistoryScreen, 320);
    lv_obj_set_height(ui_wateringHistoryScreen, 240);
    lv_obj_set_align(ui_wateringHistoryScreen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wateringHistoryScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_wateringHistoryScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_wateringHistoryScreen,
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_wateringHistoryScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_wateringHistoryScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wateringHistoryScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wateringHistoryScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wateringHistoryScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wateringHistoryScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wateringHistoryScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wateringHistoryScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleWateringHistory = lv_label_create(ui_wateringHistoryScreen);
    lv_obj_set_width(ui_LabelTitleWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleWateringHistory, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleWateringHistory, "Watering History");
    lv_obj_set_style_text_color(ui_LabelTitleWateringHistory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleWateringHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHeaderWateringHistoryContainer = lv_obj_create(ui_wateringHistoryScreen);
    lv_obj_set_width(ui_PanelHeaderWateringHistoryContainer, 300);
    lv_obj_set_height(ui_PanelHeaderWateringHistoryContainer, 50);
    lv_obj_set_align(ui_PanelHeaderWateringHistoryContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PanelHeaderWateringHistoryContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelHeaderWateringHistoryContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelHeaderWateringHistoryContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_PanelHeaderWateringHistoryContainer, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelHeaderWateringHistoryContainer, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PanelHeaderWateringHistoryContainer, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeaderWateringHistoryContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHeaderWateringHistoryContainer, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeaderWateringHistoryContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelHeaderWateringHistoryContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelHeaderWateringHistoryContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelHeaderWateringHistoryContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelHeaderWateringHistoryContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPreviousHeaderWateringHistory = lv_btn_create(ui_PanelHeaderWateringHistoryContainer);
    lv_obj_set_width(ui_ButtonPreviousHeaderWateringHistory, 40);
    lv_obj_set_height(ui_ButtonPreviousHeaderWateringHistory, 40);
    lv_obj_set_align(ui_ButtonPreviousHeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPreviousHeaderWateringHistory, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPreviousHeaderWateringHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPreviousHeaderWateringHistory = lv_label_create(ui_ButtonPreviousHeaderWateringHistory);
    lv_obj_set_width(ui_LabelPreviousHeaderWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreviousHeaderWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPreviousHeaderWateringHistory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreviousHeaderWateringHistory, "<");

    ui_PanelHeaderWateringHistory = lv_obj_create(ui_PanelHeaderWateringHistoryContainer);
    lv_obj_set_width(ui_PanelHeaderWateringHistory, 200);
    lv_obj_set_height(ui_PanelHeaderWateringHistory, 40);
    lv_obj_set_x(ui_PanelHeaderWateringHistory, 222);
    lv_obj_set_y(ui_PanelHeaderWateringHistory, 25);
    lv_obj_set_align(ui_PanelHeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelHeaderWateringHistory, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelHeaderWateringHistory, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_PanelHeaderWateringHistory,
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW | LV_OBJ_FLAG_SCROLL_ONE);    /// Flags
    lv_obj_set_scrollbar_mode(ui_PanelHeaderWateringHistory, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_PanelHeaderWateringHistory, LV_DIR_HOR);
    lv_obj_set_style_bg_color(ui_PanelHeaderWateringHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeaderWateringHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHeaderWateringHistory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeaderWateringHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelHeaderWateringHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelHeaderWateringHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelHeaderWateringHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelHeaderWateringHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PanelHeaderWateringHistory, lv_color_hex(0xFFFFFF),
                                  LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHeaderWateringHistory, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PanelItem1HeaderWateringHistory = lv_obj_create(ui_PanelHeaderWateringHistory);
    lv_obj_set_width(ui_PanelItem1HeaderWateringHistory, 35);
    lv_obj_set_height(ui_PanelItem1HeaderWateringHistory, 35);
    lv_obj_set_align(ui_PanelItem1HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelItem1HeaderWateringHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelItem1HeaderWateringHistory, lv_color_hex(0x4264FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelItem1HeaderWateringHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_PanelItem1HeaderWateringHistory, LV_OBJ_FLAG_HIDDEN);


    ui_LabelItem1HeaderWateringHistory = lv_label_create(ui_PanelItem1HeaderWateringHistory);
    lv_obj_set_width(ui_LabelItem1HeaderWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelItem1HeaderWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelItem1HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelItem1HeaderWateringHistory, "1");

    ui_PanelItem2HeaderWateringHistory = lv_obj_create(ui_PanelHeaderWateringHistory);
    lv_obj_set_width(ui_PanelItem2HeaderWateringHistory, 35);
    lv_obj_set_height(ui_PanelItem2HeaderWateringHistory, 35);
    lv_obj_set_align(ui_PanelItem2HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelItem2HeaderWateringHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_PanelItem2HeaderWateringHistory, LV_OBJ_FLAG_HIDDEN);

    ui_LabelItem2HeaderWateringHistory = lv_label_create(ui_PanelItem2HeaderWateringHistory);
    lv_obj_set_width(ui_LabelItem2HeaderWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelItem2HeaderWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelItem2HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelItem2HeaderWateringHistory, "2");

    ui_PanelItem3HeaderWateringHistory = lv_obj_create(ui_PanelHeaderWateringHistory);
    lv_obj_set_width(ui_PanelItem3HeaderWateringHistory, 35);
    lv_obj_set_height(ui_PanelItem3HeaderWateringHistory, 35);
    lv_obj_set_align(ui_PanelItem3HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelItem3HeaderWateringHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_PanelItem3HeaderWateringHistory, LV_OBJ_FLAG_HIDDEN);

    ui_LabelItem3HeaderWateringHistory = lv_label_create(ui_PanelItem3HeaderWateringHistory);
    lv_obj_set_width(ui_LabelItem3HeaderWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelItem3HeaderWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelItem3HeaderWateringHistory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelItem3HeaderWateringHistory, "3");

    ui_ButtonNextHeaderWateringHistory = lv_btn_create(ui_PanelHeaderWateringHistoryContainer);
    lv_obj_set_width(ui_ButtonNextHeaderWateringHistory, 40);
    lv_obj_set_height(ui_ButtonNextHeaderWateringHistory, 40);
    lv_obj_set_align(ui_ButtonNextHeaderWateringHistory, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNextHeaderWateringHistory, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNextHeaderWateringHistory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelNextHeaderWateringHistory = lv_label_create(ui_ButtonNextHeaderWateringHistory);
    lv_obj_set_width(ui_LabelNextHeaderWateringHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNextHeaderWateringHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelNextHeaderWateringHistory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNextHeaderWateringHistory, ">");

    ui_PanelWateringHistoryItem1 = lv_obj_create(ui_wateringHistoryScreen);
    lv_obj_set_width(ui_PanelWateringHistoryItem1, 310);
    lv_obj_set_height(ui_PanelWateringHistoryItem1, 70);
    lv_obj_set_x(ui_PanelWateringHistoryItem1, -11);
    lv_obj_set_y(ui_PanelWateringHistoryItem1, 101);
    lv_obj_set_align(ui_PanelWateringHistoryItem1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWateringHistoryItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameWateringHistoryItem1 = lv_label_create(ui_PanelWateringHistoryItem1);
    lv_obj_set_width(ui_LabelNameWateringHistoryItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWateringHistoryItem1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWateringHistoryItem1, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWateringHistoryItem1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAreaWateringHistoryItem1 = lv_label_create(ui_PanelWateringHistoryItem1);
    lv_obj_set_width(ui_LabelAreaWateringHistoryItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAreaWateringHistoryItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAreaWateringHistoryItem1, 0);
    lv_obj_set_y(ui_LabelAreaWateringHistoryItem1, 15);
    lv_label_set_text(ui_LabelAreaWateringHistoryItem1, "Area 1");
    lv_obj_set_style_text_font(ui_LabelAreaWateringHistoryItem1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelResultWaterQuantityWateringHistoryItem1 = lv_label_create(ui_PanelWateringHistoryItem1);
    lv_obj_set_width(ui_LabelResultWaterQuantityWateringHistoryItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResultWaterQuantityWateringHistoryItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelResultWaterQuantityWateringHistoryItem1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelResultWaterQuantityWateringHistoryItem1, "SUCCESS");
    lv_obj_set_style_text_font(ui_LabelResultWaterQuantityWateringHistoryItem1, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStartTimeWateringHistoryItem1 = lv_obj_create(ui_PanelWateringHistoryItem1);
    lv_obj_set_width(ui_PanelStartTimeWateringHistoryItem1, 120);
    lv_obj_set_height(ui_PanelStartTimeWateringHistoryItem1, 20);
    lv_obj_set_x(ui_PanelStartTimeWateringHistoryItem1, 0);
    lv_obj_set_y(ui_PanelStartTimeWateringHistoryItem1, -5);
    lv_obj_set_align(ui_PanelStartTimeWateringHistoryItem1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelStartTimeWateringHistoryItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelStartTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelStartTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelStartTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelStartTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWateringHistoryItem1 = lv_label_create(ui_PanelStartTimeWateringHistoryItem1);
    lv_obj_set_width(ui_LabelStartTimeWateringHistoryItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWateringHistoryItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStartTimeWateringHistoryItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWateringHistoryItem1, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWateringHistoryItem1, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEndTimeWateringHistoryItem1 = lv_obj_create(ui_PanelWateringHistoryItem1);
    lv_obj_set_width(ui_PanelEndTimeWateringHistoryItem1, 120);
    lv_obj_set_height(ui_PanelEndTimeWateringHistoryItem1, 20);
    lv_obj_set_x(ui_PanelEndTimeWateringHistoryItem1, 125);
    lv_obj_set_y(ui_PanelEndTimeWateringHistoryItem1, -5);
    lv_obj_set_align(ui_PanelEndTimeWateringHistoryItem1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelEndTimeWateringHistoryItem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelEndTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEndTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEndTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEndTimeWateringHistoryItem1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWateringHistoryItem1 = lv_label_create(ui_PanelEndTimeWateringHistoryItem1);
    lv_obj_set_width(ui_LabelEndTimeWateringHistoryItem1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWateringHistoryItem1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEndTimeWateringHistoryItem1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWateringHistoryItem1, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWateringHistoryItem1, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWateringHistoryItem2 = lv_obj_create(ui_wateringHistoryScreen);
    lv_obj_set_width(ui_PanelWateringHistoryItem2, 310);
    lv_obj_set_height(ui_PanelWateringHistoryItem2, 70);
    lv_obj_set_x(ui_PanelWateringHistoryItem2, -11);
    lv_obj_set_y(ui_PanelWateringHistoryItem2, 101);
    lv_obj_set_align(ui_PanelWateringHistoryItem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWateringHistoryItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameWateringHistoryItem2 = lv_label_create(ui_PanelWateringHistoryItem2);
    lv_obj_set_width(ui_LabelNameWateringHistoryItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWateringHistoryItem2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWateringHistoryItem2, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWateringHistoryItem2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAreaWateringHistoryItem2 = lv_label_create(ui_PanelWateringHistoryItem2);
    lv_obj_set_width(ui_LabelAreaWateringHistoryItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAreaWateringHistoryItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAreaWateringHistoryItem2, 0);
    lv_obj_set_y(ui_LabelAreaWateringHistoryItem2, 15);
    lv_label_set_text(ui_LabelAreaWateringHistoryItem2, "Area 1");
    lv_obj_set_style_text_font(ui_LabelAreaWateringHistoryItem2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelResultWaterQuantityWateringHistoryItem2 = lv_label_create(ui_PanelWateringHistoryItem2);
    lv_obj_set_width(ui_LabelResultWaterQuantityWateringHistoryItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResultWaterQuantityWateringHistoryItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelResultWaterQuantityWateringHistoryItem2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelResultWaterQuantityWateringHistoryItem2, "FAILED");
    lv_obj_set_style_text_font(ui_LabelResultWaterQuantityWateringHistoryItem2, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStartTimeWateringHistoryItem2 = lv_obj_create(ui_PanelWateringHistoryItem2);
    lv_obj_set_width(ui_PanelStartTimeWateringHistoryItem2, 120);
    lv_obj_set_height(ui_PanelStartTimeWateringHistoryItem2, 20);
    lv_obj_set_x(ui_PanelStartTimeWateringHistoryItem2, 0);
    lv_obj_set_y(ui_PanelStartTimeWateringHistoryItem2, -5);
    lv_obj_set_align(ui_PanelStartTimeWateringHistoryItem2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelStartTimeWateringHistoryItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelStartTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelStartTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelStartTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelStartTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWateringHistoryItem2 = lv_label_create(ui_PanelStartTimeWateringHistoryItem2);
    lv_obj_set_width(ui_LabelStartTimeWateringHistoryItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWateringHistoryItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStartTimeWateringHistoryItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWateringHistoryItem2, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWateringHistoryItem2, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEndTimeWateringHistoryItem2 = lv_obj_create(ui_PanelWateringHistoryItem2);
    lv_obj_set_width(ui_PanelEndTimeWateringHistoryItem2, 120);
    lv_obj_set_height(ui_PanelEndTimeWateringHistoryItem2, 20);
    lv_obj_set_x(ui_PanelEndTimeWateringHistoryItem2, 125);
    lv_obj_set_y(ui_PanelEndTimeWateringHistoryItem2, -5);
    lv_obj_set_align(ui_PanelEndTimeWateringHistoryItem2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelEndTimeWateringHistoryItem2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelEndTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEndTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEndTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEndTimeWateringHistoryItem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWateringHistoryItem2 = lv_label_create(ui_PanelEndTimeWateringHistoryItem2);
    lv_obj_set_width(ui_LabelEndTimeWateringHistoryItem2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWateringHistoryItem2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEndTimeWateringHistoryItem2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWateringHistoryItem2, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWateringHistoryItem2, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWateringHistoryItem3 = lv_obj_create(ui_wateringHistoryScreen);
    lv_obj_set_width(ui_PanelWateringHistoryItem3, 310);
    lv_obj_set_height(ui_PanelWateringHistoryItem3, 70);
    lv_obj_set_x(ui_PanelWateringHistoryItem3, -11);
    lv_obj_set_y(ui_PanelWateringHistoryItem3, 101);
    lv_obj_set_align(ui_PanelWateringHistoryItem3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWateringHistoryItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNameWateringHistoryItem3 = lv_label_create(ui_PanelWateringHistoryItem3);
    lv_obj_set_width(ui_LabelNameWateringHistoryItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNameWateringHistoryItem3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelNameWateringHistoryItem3, "Schedule 1");
    lv_obj_set_style_text_font(ui_LabelNameWateringHistoryItem3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAreaWateringHistoryItem3 = lv_label_create(ui_PanelWateringHistoryItem3);
    lv_obj_set_width(ui_LabelAreaWateringHistoryItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAreaWateringHistoryItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAreaWateringHistoryItem3, 0);
    lv_obj_set_y(ui_LabelAreaWateringHistoryItem3, 15);
    lv_label_set_text(ui_LabelAreaWateringHistoryItem3, "Area 1");
    lv_obj_set_style_text_font(ui_LabelAreaWateringHistoryItem3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelResultWaterQuantityWateringHistoryItem3 = lv_label_create(ui_PanelWateringHistoryItem3);
    lv_obj_set_width(ui_LabelResultWaterQuantityWateringHistoryItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelResultWaterQuantityWateringHistoryItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelResultWaterQuantityWateringHistoryItem3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelResultWaterQuantityWateringHistoryItem3, "SUCCESS");
    lv_obj_set_style_text_font(ui_LabelResultWaterQuantityWateringHistoryItem3, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStartTimeWateringHistoryItem3 = lv_obj_create(ui_PanelWateringHistoryItem3);
    lv_obj_set_width(ui_PanelStartTimeWateringHistoryItem3, 120);
    lv_obj_set_height(ui_PanelStartTimeWateringHistoryItem3, 20);
    lv_obj_set_x(ui_PanelStartTimeWateringHistoryItem3, 0);
    lv_obj_set_y(ui_PanelStartTimeWateringHistoryItem3, -5);
    lv_obj_set_align(ui_PanelStartTimeWateringHistoryItem3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelStartTimeWateringHistoryItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelStartTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelStartTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelStartTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelStartTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartTimeWateringHistoryItem3 = lv_label_create(ui_PanelStartTimeWateringHistoryItem3);
    lv_obj_set_width(ui_LabelStartTimeWateringHistoryItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartTimeWateringHistoryItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStartTimeWateringHistoryItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStartTimeWateringHistoryItem3, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelStartTimeWateringHistoryItem3, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelEndTimeWateringHistoryItem3 = lv_obj_create(ui_PanelWateringHistoryItem3);
    lv_obj_set_width(ui_PanelEndTimeWateringHistoryItem3, 120);
    lv_obj_set_height(ui_PanelEndTimeWateringHistoryItem3, 20);
    lv_obj_set_x(ui_PanelEndTimeWateringHistoryItem3, 125);
    lv_obj_set_y(ui_PanelEndTimeWateringHistoryItem3, -5);
    lv_obj_set_align(ui_PanelEndTimeWateringHistoryItem3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelEndTimeWateringHistoryItem3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelEndTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelEndTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelEndTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelEndTimeWateringHistoryItem3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEndTimeWateringHistoryItem3 = lv_label_create(ui_PanelEndTimeWateringHistoryItem3);
    lv_obj_set_width(ui_LabelEndTimeWateringHistoryItem3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEndTimeWateringHistoryItem3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelEndTimeWateringHistoryItem3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEndTimeWateringHistoryItem3, "2024-08-01 04:00");
    lv_obj_set_style_text_font(ui_LabelEndTimeWateringHistoryItem3, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_PanelLoadingWateringHistoryScreen = lv_obj_create(ui_wateringHistory);
    lv_obj_set_width(ui_PanelLoadingWateringHistoryScreen, 320);
    lv_obj_set_height(ui_PanelLoadingWateringHistoryScreen, 240);
    lv_obj_set_align(ui_PanelLoadingWateringHistoryScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLoadingWateringHistoryScreen, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_PanelLoadingWateringHistoryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLoadingWateringHistoryScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLoadingWateringHistoryScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerLoadingWateringHistoryScreen = lv_spinner_create(ui_PanelLoadingWateringHistoryScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerLoadingWateringHistoryScreen, 80);
    lv_obj_set_height(ui_SpinnerLoadingWateringHistoryScreen, 80);
    lv_obj_set_align(ui_SpinnerLoadingWateringHistoryScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLoadingWateringHistoryScreen, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_LabelLoadingWateringHistoryScreen = lv_label_create(ui_PanelLoadingWateringHistoryScreen);
    lv_obj_set_width(ui_LabelLoadingWateringHistoryScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoadingWateringHistoryScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoadingWateringHistoryScreen, 0);
    lv_obj_set_y(ui_LabelLoadingWateringHistoryScreen, 75);
    lv_obj_set_align(ui_LabelLoadingWateringHistoryScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoadingWateringHistoryScreen, "Loading...");
    lv_obj_set_style_text_color(ui_LabelLoadingWateringHistoryScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoadingWateringHistoryScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);   

    lv_obj_add_event_cb(ui_wateringHistory, ui_event_wateringHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelItem1HeaderWateringHistory, ui_event_PanelItem1HeaderWateringHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelItem2HeaderWateringHistory, ui_event_PanelItem2HeaderWateringHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelItem3HeaderWateringHistory, ui_event_PanelItem3HeaderWateringHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPreviousHeaderWateringHistory, ui_event_ButtonPreviousHeaderWateringHistory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNextHeaderWateringHistory, ui_event_ButtonNextHeaderWateringHistory, LV_EVENT_ALL, NULL);
}
