// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "../ui.h"

void ui_waterQuantity_screen_init(void)
{
    ui_waterQuantity = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_waterQuantity, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_waterQuantity, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_waterQuantity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waterQuantity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_waterQuantity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_waterQuantity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterQuantityScheduleItemScreen = lv_obj_create(ui_waterQuantity);
    lv_obj_set_width(ui_WaterQuantityScheduleItemScreen, 320);
    lv_obj_set_height(ui_WaterQuantityScheduleItemScreen, 240);
    lv_obj_set_align(ui_WaterQuantityScheduleItemScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WaterQuantityScheduleItemScreen,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_WaterQuantityScheduleItemScreen, LV_DIR_VER);
    lv_obj_set_style_radius(ui_WaterQuantityScheduleItemScreen, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WaterQuantityScheduleItemScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterQuantityScheduleItemScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleWaterQuantityScheduleItem = lv_label_create(ui_WaterQuantityScheduleItemScreen);
    lv_obj_set_width(ui_LabelTitleWaterQuantityScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleWaterQuantityScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitleWaterQuantityScheduleItem, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleWaterQuantityScheduleItem, "Water Quantity");
    lv_obj_set_style_text_color(ui_LabelTitleWaterQuantityScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCloseButtonWaterQuantityScheduleItem = lv_obj_create(ui_WaterQuantityScheduleItemScreen);
    lv_obj_set_width(ui_PanelCloseButtonWaterQuantityScheduleItem, 30);
    lv_obj_set_height(ui_PanelCloseButtonWaterQuantityScheduleItem, 30);
    lv_obj_set_x(ui_PanelCloseButtonWaterQuantityScheduleItem, 136);
    lv_obj_set_y(ui_PanelCloseButtonWaterQuantityScheduleItem, -100);
    lv_obj_set_align(ui_PanelCloseButtonWaterQuantityScheduleItem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCloseButtonWaterQuantityScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCloseButtonWaterQuantityScheduleItem, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCloseButtonWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCloseButtonWaterQuantityScheduleItem = lv_label_create(ui_PanelCloseButtonWaterQuantityScheduleItem);
    lv_obj_set_width(ui_LabelCloseButtonWaterQuantityScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCloseButtonWaterQuantityScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCloseButtonWaterQuantityScheduleItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCloseButtonWaterQuantityScheduleItem, "X");
    lv_obj_set_style_text_color(ui_LabelCloseButtonWaterQuantityScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCloseButtonWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_PanelTextAreaWaterQuantityScheduleItem = lv_obj_create(ui_WaterQuantityScheduleItemScreen);
    lv_obj_set_width(ui_PanelTextAreaWaterQuantityScheduleItem, 300);
    lv_obj_set_height(ui_PanelTextAreaWaterQuantityScheduleItem, 50);
    lv_obj_set_x(ui_PanelTextAreaWaterQuantityScheduleItem, 0);
    lv_obj_set_y(ui_PanelTextAreaWaterQuantityScheduleItem, -60);
    lv_obj_set_align(ui_PanelTextAreaWaterQuantityScheduleItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTextAreaWaterQuantityScheduleItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTextAreaWaterQuantityScheduleItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelTextAreaWaterQuantityScheduleItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTextAreaWaterQuantityScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTextAreaWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTextAreaWaterQuantityScheduleItem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTextAreaWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTextAreaWaterQuantityScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTextAreaWaterQuantityScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTextAreaWaterQuantityScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTextAreaWaterQuantityScheduleItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_TextAreaWaterQuantityScheduleItem = lv_textarea_create(ui_PanelTextAreaWaterQuantityScheduleItem);
    lv_obj_set_width(ui_TextAreaWaterQuantityScheduleItem, 226);
    lv_obj_set_height(ui_TextAreaWaterQuantityScheduleItem, 37);
    lv_obj_set_x(ui_TextAreaWaterQuantityScheduleItem, 7);
    lv_obj_set_y(ui_TextAreaWaterQuantityScheduleItem, 26);
    lv_obj_set_align(ui_TextAreaWaterQuantityScheduleItem, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaWaterQuantityScheduleItem, "111");
    lv_textarea_set_placeholder_text(ui_TextAreaWaterQuantityScheduleItem, "Enter here...");

    ui_LabelUnitWaterQuantityScheduleItem = lv_label_create(ui_PanelTextAreaWaterQuantityScheduleItem);
    lv_obj_set_width(ui_LabelUnitWaterQuantityScheduleItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnitWaterQuantityScheduleItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnitWaterQuantityScheduleItem, 121);
    lv_obj_set_y(ui_LabelUnitWaterQuantityScheduleItem, 34);
    lv_obj_set_align(ui_LabelUnitWaterQuantityScheduleItem, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelUnitWaterQuantityScheduleItem, "(ml)");
    lv_obj_set_style_text_color(ui_LabelUnitWaterQuantityScheduleItem, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnitWaterQuantityScheduleItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnitWaterQuantityScheduleItem, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardWaterQuantityScheduleItem = lv_keyboard_create(ui_WaterQuantityScheduleItemScreen);
    lv_keyboard_set_mode(ui_KeyboardWaterQuantityScheduleItem, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardWaterQuantityScheduleItem, 310);
    lv_obj_set_height(ui_KeyboardWaterQuantityScheduleItem, 149);
    lv_obj_set_x(ui_KeyboardWaterQuantityScheduleItem, 0);
    lv_obj_set_y(ui_KeyboardWaterQuantityScheduleItem, 10);
    lv_obj_set_align(ui_KeyboardWaterQuantityScheduleItem, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_PanelCloseButtonWaterQuantityScheduleItem, ui_event_PanelCloseButtonWaterQuantityScheduleItem,
                        LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardWaterQuantityScheduleItem, ui_TextAreaWaterQuantityScheduleItem);

}
