// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
void change_screen_mqtt(lv_event_t * e);
void scan_network(lv_event_t * e);
void button1_on(lv_event_t * e);
void button1_off(lv_event_t * e);
void button2_on(lv_event_t * e);
void button2_off(lv_event_t * e);
void change_brightness(lv_event_t * e);
void change_screen_ota(lv_event_t * e);
void handle_out_ota_page();
void handle_start_ota();
void schedule_screen_init(lv_event_t * e);
void deleteObject(lv_obj_t * obj);
void ui_event_DropdownClickedScheduleRepeatScheduleItem(lv_event_t * e);
void ui_event_CheckboxScheduleEndDateScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemMondayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemTuesdayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemWednesdayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemThursdayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemFridayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemSaturdayScheduleItem(lv_event_t * e);
void ui_event_PanelScheduleWeekItemSundayScheduleItem(lv_event_t * e);
void ui_event_ButtonOKHeaderScheduleItem(lv_event_t * e);
void ui_event_ButtonCancelHeaderScheduleItem(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
